controllers/factory/scrapes_build.go, controllers/factory/scrapes_build_test.go
If cert or ca is empty, nothing will be added to config file.
=> #64 fixed tlsConfig logic

config/manager/kustomization.yaml, config/manager/namespace.yaml, docs/kustomize-example/kustomization.yaml, docs/kustomize-example/manager.patch.yaml, docs/quick-start.MD
Closes #70 
Signed-off-by: Mario Vejlupek <mario@vejlupek.cz>
=> Docs add kustomize instalation

.github/workflows/main.yaml, .github/workflows/release.yaml, Docker-alphine, Makefile, controllers/factory/vmsingle.go
fixed small typo at vmsingle deploy
=> added cross complilation with docker #71

config/examples/vmalertmanager.yaml
See Alermanager docs for reference https://prometheus.io/docs/alerting/latest/configuration/#configuration-file
=> Fix alertmanager example indention

internal/config/config.go
=> Update prometheus-config-reloader to v0.42.0

config/examples/vmagent_tls.yaml, controllers/factory/vmcluster.go
- Fixed field in vmagent example
- Fixed vmselect args logic
=> fixed  vmselect args

controllers/factory/vmagent.go, controllers/factory/vmalert.go
for vmagent and vmalert
https://github.com/VictoriaMetrics/operator/issues/97
=> fixes volumes mount

api/v1beta1/vmalert_types.go, controllers/factory/rulescm.go, controllers/factory/rulescm_test.go, docs/quick-start.MD, go.mod, go.sum
https://github.com/VictoriaMetrics/operator/issues/99
operator.victoriametrics.com/vmalert-deduplicate-rules - add it with non empty value to vmalert annotation
=> adds dedup annototations for vmalert

.github/workflows/main.yaml, .github/workflows/release.yaml, config/rbac/role.yaml, controllers/factory/scrapes.go, controllers/factory/vmagent.go, controllers/vmagent_controller.go, controllers/vmalert_controller.go, controllers/vmalertmanager_controller.go, controllers/vmcluster_controller.go, controllers/vmsingle_controller.go
adds temp dir for vmagent with storage limit
https://github.com/VictoriaMetrics/operator/issues/106
=> fixes rbac for openshift,

controllers/factory/probe_build.go, controllers/factory/probe_build_test.go
https://github.com/VictoriaMetrics/operator/issues/125
=> fixes probe build

controllers/converter/apis.go, controllers/converter/apis_test.go, docs/api.MD
https://github.com/VictoriaMetrics/operator/issues/144
updates api doc
=> fixes servername conversion

controllers/factory/vmcluster.go
https://github.com/VictoriaMetrics/operator/issues/147
=> Fix nil map panic for annotations

controllers/factory/scrapes_build.go, controllers/factory/scrapes_build_test.go
by default, use __address__ from vmagent
=> changes config genertion for nodescrape,

controllers/factory/scrapes.go, controllers/factory/vmagent/rbac.go
fixes race for self serviceScrape update
=> fixes vmagent role update

config/rbac/role.yaml, controllers/factory/alertmanager.go
perform manual rolling update with OnDelete strategy,
allow to change pvc value for it
adds missing RBAC for storageclass
=> updates vmalertmanager statefulset update

controllers/factory/alertmanager.go, controllers/factory/expansion.go, controllers/factory/expansion_test.go, controllers/factory/vmcluster.go, controllers/factory/vmsingle.go
fixes bug with update for cluster and alertmanager
=> removes linevess probe from storage and single node

api/v1beta1/vmsingle_types.go, config/crd/bases/operator.victoriametrics.com_vmsingles.yaml, controllers/factory/vmsingle.go
Hello. I would want customize vmsingle deployment probes. Can we add this?
=> Adding customizable probes support for vmsingle

controllers/factory/expansion.go
Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>
According to the last commit 306b1014bb0db97a7ed298bbe12cb22637978412, we will diff pvc objects.
But the following resize check would be unreachable.
Relate to issue #205
=> Check storage resize first

api/v1beta1/vmservicescrape_types.go, controllers/factory/vmagent.go, controllers/factory/vmagent_test.go
https://github.com/VictoriaMetrics/operator/issues/215
adds more test cases for builder
proper handle missing values
=> Fixes bug with tlsConfig build for vmagent

controllers/factory/vmagent.go, controllers/vmagent_controller.go
https://github.com/VictoriaMetrics/operator/issues/222
Its first part of changes.
=> fixes relabelingConfig watch for vmagent

api/v1beta1/vmservicescrape_types.go, controllers/factory/scrapes_build_test.go, controllers/factory/vmagent.go, controllers/factory/vmalert.go, controllers/factory/vmalert_test.go
fixes flag build for tlsConfig
https://github.com/VictoriaMetrics/operator/issues/224
=> fixes panic for tlsConfig

api/v1beta1/vmagent_types.go, api/v1beta1/vmservicescrape_types.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/operator.victoriametrics.com_vmagents.yaml, controllers/factory/finalize/vmagent.go, controllers/factory/scrapes_build.go, controllers/factory/vmagent.go, controllers/factory/vmagent_test.go, controllers/factory/vmsingle.go, docs/relabeling.MD
https://github.com/VictoriaMetrics/operator/issues/154
=> adds inline relabeling config for vmagent

controllers/factory/vmagent.go, controllers/factory/vmagent_test.go, docs/api.MD, internal/config/config.go, vars.MD
it must fix breaking changes from prometheus-config-reloader
https://github.com/VictoriaMetrics/operator/issues/259
=> adds version detection for vmagent config reloader

api/v1beta1/vmagent_types.go, api/v1beta1/vmalert_types.go, api/v1beta1/vmalertmanager_types.go, api/v1beta1/vmauth_types.go, api/v1beta1/vmcluster_types.go, api/v1beta1/vmsingle_types.go, controllers/factory/vmcluster_test.go
fixes panic https://github.com/VictoriaMetrics/operator/issues/264
=> refactors labels merge

docs/quick-start.MD
Hi, while trying the VictoriaMetrics operator and following the quick start docs, I found some typos. Anyway, thanks for creating this awesome operator.
=> Fix some typos on quick start docs

controllers/factory/alertmanager.go
Changes order for rollingUpdate call.
=> Fixes vmalertmanager update process 

controllers/factory/scrapes_build.go
hi, I want to make a suggestion to modify the implementation of VMPodScrape.spec.selector from relabel_configs to kubernetesSDConfig.selector.
In our cases, if we use relabels_config, then it will list all pods from specified namespace,s even all namespaces, this will make a big pressure for apiserver if the k8s cluster has many nodes and pods.
=> modify the implementation of VMPodScrape.spec.selector

config/rbac/role.yaml, controllers/factory/psp/psp.go, internal/manager/manager.go
=> Fixes openshift sa reconcile

api/v1beta1/vmauth_types.go, api/v1beta1/vmuser_types.go, config/crd/bases/operator.victoriametrics.com_vmauths.yaml, config/crd/bases/operator.victoriametrics.com_vmusers.yaml, controllers/factory/vmuser.go, controllers/factory/vmuser_test.go
adds `url_path_suffix`  for https://github.com/VictoriaMetrics/operator/issues/245
use simple url_prefix instead of url_map in default case
=> changes vmauth config generation

controllers/factory/k8stools/client_utils.go, controllers/factory/psp/psp.go, controllers/factory/scrapes.go, controllers/factory/vmagent.go, controllers/factory/vmagent/rbac.go, controllers/factory/vmagent/rbac_test.go, controllers/factory/vmalert.go, controllers/factory/vmalert_test.go, controllers/factory/vmauth/rbac.go, controllers/vmagent_controller.go, controllers/vmalert_controller.go, controllers/vmalertmanager_controller.go, controllers/vmauth_controller.go, controllers/vmuser_controller.go, internal/manager/manager.go
it must reduce memory usage https://github.com/VictoriaMetrics/operator/issues/285
=> limits client.List call to CR namespace

Makefile, config/crd/bases/operator.victoriametrics.com_vmagents.yaml, config/crd/bases/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/bases/operator.victoriametrics.com_vmalerts.yaml, config/crd/bases/operator.victoriametrics.com_vmauths.yaml, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, config/crd/bases/operator.victoriametrics.com_vmsingles.yaml, config/crd/legacy/operator.victoriametrics.com_vmagents.yaml, config/crd/legacy/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, config/crd/legacy/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/legacy/operator.victoriametrics.com_vmalerts.yaml, config/crd/legacy/operator.victoriametrics.com_vmauths.yaml, config/crd/legacy/operator.victoriametrics.com_vmclusters.yaml, config/crd/legacy/operator.victoriametrics.com_vmsingles.yaml
https://github.com/VictoriaMetrics/operator/issues/316
=> fixes CRD generation 

Makefile, config/crd/bases/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, config/crd/legacy/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, config/examples/vmalertmanager_config.yaml
https://github.com/VictoriaMetrics/helm-charts/issues/199
=> fixes AlertmanagerConfig CRD

internal/config-reloader/main.go, internal/manager/manager.go
Fixed some typos I've found when working on other PRs
=> Fix several typos

api/v1beta1/vmstaticscrape_types.go, controllers/factory/scrapes.go, controllers/factory/static_targets_build.go
https://github.com/VictoriaMetrics/operator/issues/337
=> fixes regression at staticScrapeConfig

controllers/converter/apis.go
https://github.com/VictoriaMetrics/operator/issues/335
=> fixes conversion for podMonitor

controllers/factory/alertmanager/config.go, controllers/factory/alertmanager/config_test.go
for VMAlertmanagerConfig
https://github.com/VictoriaMetrics/operator/issues/339
=> fixes slack_configs generation

api/v1beta1/vmnodescrape_types.go, api/v1beta1/vmpodscrape_types.go, api/v1beta1/vmprobe_types.go, api/v1beta1/vmservicescrape_types.go, api/v1beta1/vmstaticscrape_types.go, config/crd/bases/operator.victoriametrics.com_vmagents.yaml, config/crd/bases/operator.victoriametrics.com_vmnodescrapes.yaml, config/crd/bases/operator.victoriametrics.com_vmpodscrapes.yaml, config/crd/bases/operator.victoriametrics.com_vmprobes.yaml, config/crd/bases/operator.victoriametrics.com_vmservicescrapes.yaml, config/crd/bases/operator.victoriametrics.com_vmstaticscrapes.yaml, config/crd/legacy/operator.victoriametrics.com_vmagents.yaml, config/crd/legacy/operator.victoriametrics.com_vmnodescrapes.yaml, config/crd/legacy/operator.victoriametrics.com_vmpodscrapes.yaml, config/crd/legacy/operator.victoriametrics.com_vmprobes.yaml, config/crd/legacy/operator.victoriametrics.com_vmservicescrapes.yaml, config/crd/legacy/operator.victoriametrics.com_vmstaticscrapes.yaml
https://github.com/VictoriaMetrics/operator/issues/365
=> adds nullable option for v1.SecretKeySelector

.github/workflows/main.yaml, .github/workflows/release.yaml
=> adds security linter for workflow

docs/quick-start.MD
=> Fix probeSelector typo in VMAgent example

controllers/factory/vmagent.go
When adding the remoteWrite.maxDiskUsagePerURL=50MB  in VMAgent spec.extraArgs for example, the operator will create the vmagent deployment with a default value of  '-remoteWrite.maxDiskUsagePerURL=1073741824' and modified value of '-remoteWrite.maxDiskUsagePerURL=50MB' in spec.args.
The yaml I used for testing is here
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
name: aecp-vmagent
spec:
extraArgs:
remoteWrite.queues: "1"
remoteWrite.maxDiskUsagePerURL: 50MB
remoteWrite:
- url: http://vminsert-vmcluster.monitoring.svc:8480/insert/0/prometheus/api/v1/write
replicaCount: 1
resources:
limits:
cpu: "1"
memory: 24Gi
requests:
cpu: 250m
memory: 350Mi
updateStrategy: RollingUpdate
```
=> Remove default maxDiskUsagePerURL value while it has been set in ExtraArgs

controllers/factory/rulescm.go, controllers/factory/rulescm_test.go
https://github.com/VictoriaMetrics/operator/issues/394
=> fixes regression for vmalert object selector

api/v1beta1/vmalertmanager_types.go, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/legacy/operator.victoriametrics.com_vmalertmanagers.yaml, controllers/factory/alertmanager.go, controllers/factory/alertmanager/config.go, controllers/factory/alertmanager/config_test.go, docs/api.MD
https://github.com/VictoriaMetrics/operator/issues/390
=> adds option for disabling namespace label matcher enforcement

api/v1beta1/vmalertmanager_types.go, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/legacy/operator.victoriametrics.com_vmalertmanagers.yaml, controllers/factory/alertmanager.go, controllers/factory/alertmanager/config.go, docs/api.MD
follow-up after e0f18dc43f4b1ea9d6c350bd0b8eeac0b5d091a2
https://github.com/VictoriaMetrics/operator/issues/390
=> renames disableNamespaceMatcher, fixes comments and docs

api/v1beta1/vmcluster_types.go, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, config/crd/bases/operator.victoriametrics.com_vmsingles.yaml, config/crd/legacy/operator.victoriametrics.com_vmclusters.yaml, config/crd/legacy/operator.victoriametrics.com_vmsingles.yaml, docs/api.MD, docs/backups.MD
The link has moved, update all references to the new location.
=> update EULA URL

controllers/factory/builders.go, controllers/factory/k8stools/annotations.go, controllers/factory/k8stools/deploy.go, controllers/factory/vmagent.go, controllers/factory/vmauth.go, controllers/factory/vmsingle.go
keeps annotations with kubernetes.io/ string
it's annotations managed by kubernetes controllers and it shouldn't be modified
=> changes annotations merge

controllers/factory/vmcluster.go
https://github.com/VictoriaMetrics/operator/issues/420
=> fixes vmservicescrape for vmsinert

controllers/factory/k8stools/version.go, internal/manager/manager.go
clean up + symbol
use default values in case of failure
https://github.com/VictoriaMetrics/operator/issues/428
=> Adds mitigation to the kubernetes server parsing

api/v1beta1/vmcluster_types.go, api/v1beta1/vmsingle_types.go, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, config/crd/bases/operator.victoriametrics.com_vmsingles.yaml, config/crd/legacy/operator.victoriametrics.com_vmclusters.yaml, config/crd/legacy/operator.victoriametrics.com_vmsingles.yaml
https://github.com/VictoriaMetrics/operator/issues/430
=> allows to set retention lower then 1 month

controllers/factory/alertmanager.go, controllers/factory/builders.go, controllers/factory/builders_test.go, controllers/factory/vmagent.go, controllers/factory/vmalert.go, controllers/factory/vmauth.go, controllers/factory/vmcluster.go, controllers/factory/vmsingle.go
it must allow to controller application by user needs and redifene arguments with user values
https://github.com/VictoriaMetrics/operator/issues/450
https://github.com/VictoriaMetrics/operator/issues/448
=> controllers/factor: allow to override default args

controllers/factory/vmsingle.go
=> Add finalizer to vmsingle deployment

api/v1beta1/vmuser_types.go, controllers/factory/vmuser.go, controllers/factory/vmuser_test.go
=> Adding Name field to VMUser

internal/config-reloader/main.go
Signed-off-by: Cosrider <cosrider7@gmail.com>
=> use builtin constant http.MethodGet

internal/config-reloader/main.go
Signed-off-by: Cosrider <cosrider7@gmail.com>
=> call Close function for gzip.NewReader

controllers/converter/apis.go, controllers/converter/apis_test.go, controllers/factory/rulescm.go, controllers/factory/scrapes.go, controllers/factory/vmagent.go, controllers/vmprometheusconverter_controller.go, hack/prom_crd/prometheus_operator_crd.yaml, internal/config/config.go
it should simplify migration from prometheus operator CRDs
https://github.com/VictoriaMetrics/operator/issues/517
=> convertes: adds conversion for alertmanager config

controllers/factory/vmsingle.go
=> controllers/factory: fix resizing of PVC for vmsingle

controllers/factory/vmalert.go
Fix #587
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
=> Prevent VMAlert secret annotations from being deleted.

controllers/factory/vmagent.go, controllers/factory/vmagent_test.go
=> fixed keepInput setting for streaming aggregation (#617)

controllers/factory/alertmanager/config.go, controllers/factory/alertmanager/config_test.go
fix https://github.com/VictoriaMetrics/operator/issues/560
1. check possible duplicate receiver/timeInterval in vmalertmanagerconfig;
2. check route's receiver/timeInterval already defined in vmalertmanagerconfig;
3. check url validity
=> vmalertmanagerconfig: add sanity check

api/v1beta1/vmalertmanagerconfig_types.go, api/victoriametrics/v1beta1/vmalertmanagerconfig_types.go, config/crd/bases/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
fix https://github.com/VictoriaMetrics/operator/issues/629
=> vmalertmanagerconfig: fix parse route error and some comments

internal/config/config.go
https://github.com/prometheus/alertmanager/releases/tag/v0.25.0
=> Bump alertmanager to v0.25.0

api/v1beta1/vmcluster_types.go, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, controllers/factory/vmcluster.go, vars.MD
=> added `clusterNativePort` field to VMSelect/VMInsert for multi-level cluster setup (#634)

controllers/factory/probe_build.go, controllers/factory/scrapes_build.go, controllers/factory/scrapes_build_test.go
=> fixed selectors for Exists and NotExists operators with empty label value

controllers/factory/vmuser.go
fix https://github.com/VictoriaMetrics/operator/issues/655
=> vmuser:fix vmselect url_map in vmuser

controllers/factory/alertmanager/config.go, controllers/factory/alertmanager/config_test.go
fix https://github.com/VictoriaMetrics/operator/issues/661
=> vmalertmanagerconfig: add validation for slack receiver url

api/v1beta1/vmcluster_types.go
fix spec change check again :(
=> vmcluster: fix cluster spec check

controllers/factory/scrapes_build.go, controllers/factory/scrapes_build_test.go
address https://github.com/VictoriaMetrics/operator/issues/697
=> fix attachMetadata value miscovert

api/v1beta1/vmservicescrape_types.go, api/victoriametrics/v1beta1/vmservicescrape_types.go, controllers/factory/vmalert.go
releated https://github.com/VictoriaMetrics/operator/issues/699
=> fix tlsCAFile args when using secret or configMap

controllers/factory/alertmanager.go, controllers/factory/alertmanager_test.go, docs/CHANGELOG.MD
address https://github.com/VictoriaMetrics/operator/issues/706
=> fix vmalertmanager default resources

docs/CHANGELOG.MD
make up changelog for https://github.com/VictoriaMetrics/operator/pull/688 and https://github.com/VictoriaMetrics/operator/pull/689
=> make up changelogs for fields change

controllers/factory/k8stools/expansion.go, controllers/factory/k8stools/expansion_test.go, controllers/factory/k8stools/sts.go, docs/CHANGELOG.MD
address https://github.com/VictoriaMetrics/operator/issues/507
statefulset should be recreated if any of the volumeClaimTemplate got changed
=> fix recreate sts check for spec.volumeClaimTemplates

docs/CHANGELOG.MD, e2e/suite/suite.go, internal/config/config.go, internal/manager/manager.go, main.go
=> add ability to print default values for all operator variables (#675)

docs/CHANGELOG.MD, e2e/suite/suite.go, internal/manager/manager.go, main.go
follow up after [PR #742](https://github.com/VictoriaMetrics/operator/pull/742) - fix error with logger flags.
=> fix error with logger flags.

docs/CHANGELOG.MD, internal/config/config.go
address https://github.com/VictoriaMetrics/operator/issues/749
turn off `EnableStrictSecurity` by default
=> turn off `EnableStrictSecurity` by default

api/v1beta1/vmagent_types.go, api/victoriametrics/v1beta1/vmagent_types.go
See https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4898#discussion_r1307447532
=> vmagent: clarify Labels param description

controllers/factory/k8stools/expansion.go, controllers/factory/k8stools/expansion_test.go, controllers/factory/k8stools/sts.go, docs/CHANGELOG.MD
pvc should be checked and updated separately when there are multiple VolumeClaimTemplates, previously it's all mixed up.
=> fix pvc expansion for sts multiple VolumeClaimTemplates

.github/workflows/docs.yaml
I think, it's really the last one )
=> Fixed docs pipeline

docs/resources/vmagent.md, docs/resources/vmalert.md, docs/resources/vmauth.md
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5352
=> docs: fix repository links for CRD examples

api/v1beta1/vmauth_types.go, config/crd/bases/operator.victoriametrics.com_vmauths.yaml, config/examples/vmauth_unmanaged.yaml, controllers/factory/vmauth.go, controllers/factory/vmauth_test.go, docs/CHANGELOG.md
it allows to use external configuration with vmauth. config changes can be tracked via extraArgs `configCheckInterval: 10s` or similar param
=> api/vmauth: adds configSecret key to the vmauth spec

controllers/converter/apis.go, controllers/converter/apis_test.go
=> fix(apis.go): add missing static config relabeling config and test case

controllers/factory/k8stools/expansion.go, controllers/factory/k8stools/expansion_test.go, controllers/factory/vmagent.go, controllers/factory/vmagent_test.go
This change fixes issue: https://github.com/VictoriaMetrics/operator/issues/917
=> feat(vmagent): set serviceName on statefulset

api/v1beta1/additional.go, api/victoriametrics/v1beta1/additional.go, config/crd/bases/operator.victoriametrics.com_vmagents.yaml, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/bases/operator.victoriametrics.com_vmalerts.yaml, config/crd/bases/operator.victoriametrics.com_vmauths.yaml, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, config/crd/bases/operator.victoriametrics.com_vmsingles.yaml
=> fixes typo at comments

api/v1beta1/additional.go, api/v1beta1/vmagent_types.go, api/v1beta1/vmalert_types.go, api/v1beta1/vmalertmanager_types.go, api/v1beta1/vmauth_types.go, api/v1beta1/vmcluster_types.go, api/v1beta1/vmsingle_types.go, controllers/controllers.go
=> feat: support pause reconciliation for cr

api/v1beta1/vmagent_types.go, api/v1beta1/vmalert_types.go, api/v1beta1/vmalertmanager_types.go, api/v1beta1/vmcluster_types.go, api/v1beta1/vmsingle_types.go, api/victoriametrics/v1beta1/vmagent_types.go, api/victoriametrics/v1beta1/vmalert_types.go, api/victoriametrics/v1beta1/vmalertmanager_types.go, api/victoriametrics/v1beta1/vmcluster_types.go, api/victoriametrics/v1beta1/vmsingle_types.go, docs/CHANGELOG.md
fix: https://github.com/VictoriaMetrics/operator/issues/960
=> vmuser: find correct service port of operator's CRD

.github/workflows/main.yaml, Makefile, config/crd/bases/operator.victoriametrics.com_vmagents.yaml, config/crd/bases/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/bases/operator.victoriametrics.com_vmalerts.yaml, config/crd/bases/operator.victoriametrics.com_vmauths.yaml, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, config/crd/bases/operator.victoriametrics.com_vmnodescrapes.yaml, config/crd/bases/operator.victoriametrics.com_vmpodscrapes.yaml, config/crd/bases/operator.victoriametrics.com_vmprobes.yaml, config/crd/bases/operator.victoriametrics.com_vmrules.yaml, config/crd/bases/operator.victoriametrics.com_vmscrapeconfigs.yaml, config/crd/bases/operator.victoriametrics.com_vmservicescrapes.yaml, config/crd/bases/operator.victoriametrics.com_vmsingles.yaml, config/crd/bases/operator.victoriametrics.com_vmstaticscrapes.yaml, config/crd/bases/operator.victoriametrics.com_vmusers.yaml
upgraded yq to version, which has arm64 docker images
diff is huge, but only ident was changed in yaml files
=> yq v2 -> v4 upgrade

Dockerfile, Makefile, config/manager/manager.yaml
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4752#discussion_r1668891562
=> removed run as user from kustomize

docs/setup.md, internal/controller/operator/factory/alertmanager/statefulset.go, internal/controller/operator/factory/vmagent/vmagent.go, internal/controller/operator/factory/vmagent/vmagent_test.go, internal/controller/operator/factory/vmauth/vmauth.go, internal/controller/operator/factory/vmauth/vmauth_test.go
=> fixed command for custom reloader

api/operator/v1beta1/vmextra_types.go, docs/CHANGELOG.md, internal/controller/operator/factory/alertmanager/rbac.go, internal/controller/operator/factory/alertmanager/statefulset.go, internal/controller/operator/factory/finalize/common.go, internal/controller/operator/factory/finalize/vmalert.go, internal/controller/operator/factory/reconcile/deploy.go, internal/controller/operator/factory/reconcile/hpa.go, internal/controller/operator/factory/reconcile/pdb.go, internal/controller/operator/factory/reconcile/service.go, internal/controller/operator/factory/reconcile/service_account.go, internal/controller/operator/factory/reconcile/statefulset.go, internal/controller/operator/factory/reconcile/statefulset_pvc_expand.go, internal/controller/operator/factory/vmagent/rbac.go, internal/controller/operator/factory/vmagent/vmagent.go, internal/controller/operator/factory/vmagent/vmagent_scrapeconfig.go, internal/controller/operator/factory/vmalert/vmalert.go, internal/controller/operator/factory/vmauth/rbac.go, internal/controller/operator/factory/vmauth/vmauth.go, internal/controller/operator/factory/vmsingle/vmsingle.go
make methods more generic and less error-prone
=> finalize: simplify finalizers API usage

docs/_index.md, docs/resources/_index.md, docs/resources/vmagent.md, docs/resources/vmalert.md, docs/resources/vmalertmanager.md, docs/resources/vmalertmanagerconfig.md, docs/resources/vmauth.md, docs/resources/vmcluster.md, docs/resources/vmnodescrape.md, docs/resources/vmpodscrape.md, docs/resources/vmprobe.md, docs/resources/vmrule.md, docs/resources/vmscrapeconfig.md, docs/resources/vmservicescrape.md, docs/resources/vmsingle.md, docs/resources/vmstaticscrape.md, docs/resources/vmuser.md
updated identifiers in docs to avoid collision
=> docs: fixed menu identifiers

config/base/kustomization.yaml, config/kind/kustomization.yaml, config/rbac/kustomization.yaml, internal/config/config.go, internal/controller/operator/controllers_test.go, internal/controller/operator/vlogs_controller_test.go, internal/controller/operator/vmscrapeconfig_controller_test.go, test/e2e/prometheus_converter_test.go, test/e2e/suite/suite.go, test/e2e/vmsingle_test.go
updated regex to exclude all crds in e2e tests from removal
=> do not delete vlogs crd in tests

docs/CHANGELOG.md, internal/manager/manager.go
made exponential rate limiter delays configurable
=> configurable client qps and burst

cmd/config-reloader/main.go, docs/CHANGELOG.md
=> added reload prefix to tls cmd flags to avoid collision

config/manifests/ci.yaml
synced olm reviewers list with operator codeowners
=> updated olm reviewers

docs/CHANGELOG.md, internal/manager/manager.go
fixes https://github.com/VictoriaMetrics/operator/issues/1106
=> added flag for webhook port configuration

docs/README.md, docs/configuration.md, docs/migration.md, docs/monitoring.md, docs/quick-start.md, docs/setup.md
use https://docs.victoriametrics.com/helm instead of github repo links
=> updated chart links

docs/api.md, docs/templates/api/type.tpl
show only basic underlying types
=> updated api docs

docs/api.md, docs/templates/api/type.tpl
reverted docs template change as it renders underlying type properly
=> reverted api docs template change

api/operator/v1beta1/vmcluster_types.go, docs/CHANGELOG.md
fixes https://github.com/VictoriaMetrics/operator/issues/1122
=> vmcluster: fixed urls storage and select components

docs/CHANGELOG.md, internal/controller/operator/vmprometheusconverter_controller.go
fixed typo in alertmanagerconfig converter
=> fixed typo alertmanagerconfig converter

config/crd/overlay/crd.yaml
follow up for https://github.com/VictoriaMetrics/operator/commit/cbe3688b768ea5f557badb8c23c6e03e7feb5f96
=> actualized CRD manifests 

config/manifests/ci.yaml
to speed up operatorhub packages publishing adding victoriametrics-bot to reviewers list
=> added bot to reviewers list

config/alerting/vmoperator-rules.yaml, docs/CHANGELOG.md
added cluster label to operator alerts for multicluster setups
=> added cluster label to alerts

docs/resources/vmcluster.md
=> updated backup manager docs

config/rbac/role.yaml
address https://github.com/VictoriaMetrics/operator/issues/1167,
sync role yaml from https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-operator/templates/role.yaml
=> doc: fix basic cluster role yaml for operator

docs/resources/vmprobe.md
- changed typo **heath** -> **health**
=> docs: Fix typo in VMProbe

docs/CHANGELOG.md
updated changelog headers format to fix docs site links
=> updated changelog headers

docs/CHANGELOG.md
added default vm components versions badges with links to a changelog
=> added badges to a changelog

docs/CHANGELOG.md, internal/config/config.go
=> updated default victorialogs image

.github/workflows/operatorhub.yaml, Makefile, config/manifests/bases/victoriametrics-operator.clusterserviceversion.yaml, config/manifests/ci.default.yaml, config/manifests/ci.fbc.yaml
migrated openshift package to file-based catalog
=> migrated openshift package to file-based catalog

docs/resources/vlogs.md
fixes https://github.com/VictoriaMetrics/operator/issues/1131
=> added vlogs docs

.github/workflows/operatorhub.yaml
=> add catalogs to PR

.github/workflows/docs.yaml, README.md
sync docs to vmdocs repo directly
=> docs: sync docs to vmdocs directly

.github/workflows/docs.yaml
fixed path that should be committed in vmdocs repo
=> docs: fixed path in docs repo

.github/workflows/docs.yaml
changed golang action working directory for docs pipeline
=> docs: change golang action working directory

PROJECT
fixes issue, that happend during the latest release
=> olm: rename projectName back

.github/workflows/operatorhub.yaml
removed manual openshift catalog build trigger
=> openshift: removed manual workflow trigger

.github/workflows/operatorhub.yaml, config/manifests/ci.yaml
updated default ci.yaml with a new openshift structure
=> openshift: update ci.yaml

test/e2e/suite/suite.go
This PR is for [#1273] @f41gh7
=> [#1273]Assert k8s cluster is localhost before execute e2e test

.github/workflows/operatorhub.yaml, .gitignore, Makefile, config/manifests/ci.yaml, config/manifests/release-config.yaml
support FBC autorelease pipeline 
https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/6164
=> openshift fbc automatic release pipeline

docs/CHANGELOG.md, internal/controller/operator/factory/vmagent/vmagent.go, internal/controller/operator/factory/vmagent/vmagent_test.go
iterating shards in a reversed order produces a shard with a negative index
=> vmagent: fixed shard upscale range

docs/resources/vmagent.md
fixes portnumber in daemonset example
=> updated port in daemonset docs

docs/quick-start.md
This is the first PR in a series. The goal is to rewrite the quick-start section completely. 
STR https://github.com/VictoriaMetrics/debug-notes/pull/2
=> docs/quick-start: Rewrite setup operator\storage sections.

docs/quick-start.md
This is the second PR in a series. The goal is to rewrite the quick-start section completely.
First one: https://github.com/VictoriaMetrics/operator/pull/1328
STR https://github.com/VictoriaMetrics/debug-notes/pull/2
=> docs/quick-start: Rewrite scrapping section.

docs/quick-start.md
Follow up on https://github.com/VictoriaMetrics/operator/pull/1331, https://github.com/VictoriaMetrics/operator/commit/e85d7e280e740f1e8fd4774c58a346942076db46
* Address review comments;
* Use Deployment for demo-app, define ports explisitly
* Add `;` to code snipets so they work on copy-paste
=> docs: quick start scrape section follow-up fixes

docs/api.md, docs/templates/api/type.tpl
=> docs/api: Display "Appears In" list to be comma-separated and shown inline on a single line.

api/operator/v1beta1/vmalertmanagerconfig_types.go, api/operator/v1beta1/vmalertmanagerconfig_types_test.go, api/operator/v1beta1/vmrule_types.go, config/crd/overlay/crd.yaml, docs/CHANGELOG.md, docs/api.md, internal/config/config.go, internal/controller/operator/factory/build/container_test.go
upgraded default config-reloader image, fixed spelling issues
=> upgrade config-reloader image. fixes #2174

docs/Makefile
=> docs: fixed image name

internal/controller/operator/factory/reconcile/statefulset_pvc_expand.go
=> Change Error log to Info for PVC size increase

Dockerfile, internal/config/print.go
embedded config.go file and removed it from dockerfile
=> embed config.go for -printDefaults

api/operator/v1/vlcluster_types.go, api/operator/v1/vlsingle_types.go, api/operator/v1beta1/vlogs_types.go, api/operator/v1beta1/vmagent_types.go, api/operator/v1beta1/vmalert_types.go, api/operator/v1beta1/vmalertmanager_types.go, api/operator/v1beta1/vmalertmanagerconfig_types.go, api/operator/v1beta1/vmauth_types.go, api/operator/v1beta1/vmcluster_types.go, api/operator/v1beta1/vmsingle_types.go, internal/controller/operator/factory/build/build.go, internal/controller/operator/factory/build/pdb.go, internal/controller/operator/factory/build/service.go, internal/controller/operator/factory/build/service_account.go, internal/controller/operator/factory/finalize/common.go, internal/controller/operator/factory/finalize/orphaned.go, internal/controller/operator/factory/finalize/orphaned_test.go, internal/controller/operator/factory/finalize/vmagent.go
removed GetNSName method as it's consistently calling GetNamespace in all implementations
=> removed redundant GetNSName method

.github/workflows/main.yaml, .github/workflows/release.yaml, api/operator/v1beta1/vmalertmanagerconfig_types.go, api/operator/v1beta1/vmextra_types.go, api/operator/v1beta1/vmprobe_types.go, api/operator/v1beta1/vmrule_types_test.go, cmd/config-reloader/main.go, config/examples/vmrule.yaml, docs/resources/vmagent.md, internal/controller/operator/controllers.go, internal/controller/operator/factory/build/cache.go, internal/controller/operator/factory/build/container.go, internal/controller/operator/factory/finalize/vmagent.go, internal/controller/operator/factory/k8stools/client_utils.go, internal/controller/operator/factory/reconcile/statefulset.go, internal/controller/operator/factory/vmagent/vmagent_scrapeconfig_test.go, internal/controller/operator/factory/vmalert/rules_test.go, internal/controller/operator/factory/vmalertmanager/alertmanager.go, internal/controller/operator/factory/vmauth/vmusers_config_test.go, internal/controller/operator/factory/vmcluster/vmcluster.go, internal/controller/operator/factory/vmsingle/vmsingle.go, internal/controller/operator/vmalert_controller.go, internal/manager/manager.go, test/e2e/childobjects/vmalertmanagerconfig_test.go, test/e2e/vmauth_test.go
All these changes are about spelling.
Changes are done to:
- code comments
- display strings
There is NO changes to code or programmatic behavior.
Enjoy !
=> Spelling Fixes

docs/resources/README.md, docs/resources/vlcluster.md, docs/resources/vmanomaly.md
added doc for vmanomaly CR
fixes https://github.com/VictoriaMetrics/operator/issues/1136
=> docs: added vmanomaly CR doc

docs/CHANGELOG.md, internal/controller/operator/factory/vmalert/vmalert.go, internal/controller/operator/factory/vmalert/vmalert_test.go
fixes https://github.com/VictoriaMetrics/operator/issues/1437
=> vmalert: properly load TLS secret into VMAlert Secret

docs/CHANGELOG.md, internal/controller/operator/factory/vmanomaly/statefulset.go, test/e2e/vmanomaly_test.go
fixes https://github.com/VictoriaMetrics/operator/issues/1434
- create shards concurrently
- run anomaly tests concurrently
=> vmanomaly: update shards concurrently

api/operator/v1beta1/vmagent_types.go, api/operator/v1beta1/vmsingle_types.go, internal/controller/operator/factory/build/build.go, internal/controller/operator/factory/build/cache.go, internal/controller/operator/factory/finalize/vmagent.go, internal/controller/operator/factory/finalize/vmsingle.go, internal/controller/operator/factory/vmagent/vmagent.go, internal/controller/operator/factory/vmagent/vmagent_test.go, internal/controller/operator/factory/vmalert/vmalert.go, internal/controller/operator/factory/vmsingle/vmsingle.go, test/e2e/childobjects/vmalertmanagerconfig_test.go, test/e2e/childobjects/vmrule_test.go, test/e2e/childobjects/vmuser_test.go
this PR shares stream aggregation volume and cmd args generation. Since stream aggregation is also a part of vmagent remote write configuration which has another logic for cmd args generation, this flags generation logic was also moved to build package.
=> refactoring: share stream aggregation config, moved VM-specific flag generation to build package

docs/resources/vmagent.md, docs/resources/vmalert.md, docs/resources/vmauth.md, docs/resources/vmcluster.md, docs/resources/vmsingle.md
replaced eula property with license in docs, update VM version to more up to date
=> docs: updated enterprise examples in docs

internal/controller/operator/factory/build/build.go, internal/controller/operator/factory/vmagent/vmagent.go, internal/controller/operator/factory/vmsingle/vmsingle.go
fixed StreamAggrVolumeTo function to mount configs properly
=> follow-up for streamaggr mount fix

.github/workflows/crds.yaml
related issue https://github.com/VictoriaMetrics/helm-charts/issues/2311
@f41gh7 @Haleygo can we merge it before the next release?
=> changed original CRD path

docs/CHANGELOG.md, internal/controller/operator/factory/vmagent/scrapeconfig.go, internal/controller/operator/factory/vmagent/scrapeconfig_test.go
fixes https://github.com/VictoriaMetrics/operator/issues/1476
=> vmagent: properly attach node metadata

docs/CHANGELOG.md, docs/enterprise.md, docs/integrations/prometheus.md, docs/resources/README.md, docs/resources/vlcluster.md, docs/resources/vmagent.md, docs/resources/vmalert.md, docs/resources/vmanomaly.md, docs/resources/vmauth.md, docs/resources/vmcluster.md, docs/resources/vmnodescrape.md, docs/resources/vmpodscrape.md, docs/resources/vmprobe.md, docs/resources/vmrule.md, docs/resources/vmscrapeconfig.md, docs/resources/vmservicescrape.md, docs/resources/vmsingle.md, docs/resources/vmstaticscrape.md, docs/resources/vmuser.md
=> docs: fixed vm docs links

docs/README.md, docs/resources/README.md
required for https://github.com/VictoriaMetrics/vmdocs/issues/164
=> docs: disable direct readme page rendering

docs/resources/README.md
https://github.com/VictoriaMetrics/vmdocs/issues/164
=> docs: exclude from sitemap

api/operator/v1/vlagent_types.go, api/operator/v1/vlcluster_types.go, api/operator/v1/vmanomaly_types.go, config/manifests/bases/victoriametrics-operator.clusterserviceversion.yaml, internal/controller/operator/factory/build/cache.go, internal/controller/operator/factory/k8stools/client_utils.go, internal/controller/operator/factory/k8stools/selectors.go, internal/controller/operator/factory/vlagent/vlagent.go, internal/controller/operator/factory/vmagent/nodescrape.go, internal/controller/operator/factory/vmagent/servicescrape.go, internal/controller/operator/vmprometheusconverter_controller.go, test/e2e/prometheus_converter_test.go, test/e2e/vmsingle_test.go
This PR consists of:
- Spelling fixes
- Removal of extra spaces
These are all in comments or presentable strings.
There is NO change in code or functionality.
Note, i also have some in the operator/v1beta folder as well that i did not add to this PR
As it was not obvious what the policy is for those contributions.
=> Spelling and empty spaces

docs/CHANGELOG.md, internal/config/config.go
update traces and anomaly default versions
=> update victoriatraces and anomaly versions
