api/v1beta1/vmagent_types.go, api/v1beta1/vmalert_types.go, api/v1beta1/vmcluster_types.go, config/examples/vmagent-full.yaml, config/examples/vmagent_tls.yaml, config/examples/vmalertmanager.yaml, controllers/converter/apis.go, controllers/converter/apis_test.go, docs/api.MD
added replacement for prometheus secrets and configmaps mount path at objects conversion,
updated docs with proper mount name paths for secrets and configmaps,
update typo at examples
=> #66 wrong mount path fix

controllers/factory/k8s-utils.go, controllers/factory/rulescm.go, controllers/factory/scrapes.go
https://github.com/VictoriaMetrics/operator/issues/86
after rules changes were detected,
operator updates vmalert pods annotation with current time
it triggers kubelet action to update mounted configmap
=> adds faster sync for vmalert rules

controllers/converter/apis.go, controllers/converter/apis_test.go, controllers/vmprometheusconverter_controller.go, e2e/prometheus_converter_test.go
now unsupported by vmagent relabel configuration will be skipped
https://github.com/VictoriaMetrics/operator/issues/92
adds force update for existing prometheus objects.
=> adds filtering for prometheus converter relabelConfig

controllers/factory/vmagent.go, controllers/factory/vmalert.go, controllers/factory/vmcluster.go, controllers/factory/vmsingle.go
k8s: 1.18.2
victoria-operator: v0.3.0
If create crd VMAlert, VMAgent, VMcluster with multiple elements in spec.extraArgs, deployment will be updated repeatedly by operator，again and again....
Though without applying new version, order of args will be changed after reconcile, cause of vm-operator generated args by looping unordered map extraArgs.
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSelect
...
spec:
extraArgs:
evaluationInternal: 10s
datasource.lookback: 1m
```
I fixed it by sorting the args array before return.
=> fixes: deployment update repeatedly

controllers/factory/vmagent.go
it must fix crush when vmagent cannot find config file during start-up:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/879
=> swaps config-reloader and vmagent at container.Spec

controllers/converter/apis.go, controllers/converter/apis_test.go, controllers/vmprometheusconverter_controller.go, docs/quick-start.MD, e2e/manager_test.go, e2e/prometheus_converter_test.go, internal/config/config.go, internal/manager/manager.go
I've noticed that removing a `PrometheusRule` doesn't make the corresponding `VMRule` deleted immediately as I've expected. As it seemed easy to code (just adding some `ownerReferences`) I've decided to have some fun and add it myself. For consistency I've updated other converters as well. Apart from e2e tests I've deployed it on some 'real' cluster and tested PrometheusRule behaviour - worked as expected.
During tests I've encountered that issue (at least I think it's an issue) with typo in prober discovery so I've fixed it as well.
Can such a feature be added? I haven't found any related information in documentation or discussion in issues (although I haven't searched a lot).
I'm not sure if this should be enabled by default. From my point of view it should, but I imagine it might break …
=> In PrometheusConverter in created objects include ownerReferences

controllers/factory/scrapes.go
VMAgent does not use nodeScrapeNamespaceSelector (and nodeScrapeSelector) correctly.
Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>
=> fix nodeScrapeNamespaceSelector behavior

api/v1beta1/vmservicescrape_types.go, config/crd/bases/operator.victoriametrics.com_vmservicescrapes.yaml, config/examples/vmservicescrape-full.yaml, config/examples/vmservicescrape_service_sd.yaml, controllers/factory/scrapes_build.go, controllers/factory/scrapes_build_test.go, docs/design.MD
it allows to choose kubernetes_sd role for filtering objects,
its possible to set role: service, role: endpoints or role: endpointslices
https://github.com/VictoriaMetrics/operator/issues/127
=> adds discoveryRole setting to VMServiceScrape

controllers/factory/vmcluster.go
If `replicationFactor` is specified in VMCluster, the operator will add `-dedup.minScrapeInterval=1ms` to vmstorage and vmselect.
If vmselect has `-dedup.minScrapeInterval` option in `extraArgs`, the operator will not add `-dedup.minScrapeInterval=1ms` and will honor `extraArgs`.
**problem**: On the other hand, even if vmstorage has `-dedup.minScrapeInterval` option is `extraArgs`, the operator will add `-dedup.minScrapeInterval=1ms`. Instead, if **vmselect** has `-dedup.minScrapeInterval` option is `extraArgs`, the operator will not add `-dedup.minScrapeInterval=1ms` to vmstorage.
It's hard to imagine that only one of the `extraArgs` in vmselect and vmstorage has the dedup option, but I think it's a good idea to fix the process.
Signed-off-by: UMEZAWA Takeshi …
=> fix dedup.minScrapeInterval behavior in case of VMCluster replication

controllers/factory/vmagent.go, controllers/factory/vmalert.go, controllers/factory/vmsingle.go
VMAlert expects args prefixed with single  `-`.
=> Fix typo in args creation for VMAgent, VMAlert and VMSingle

controllers/factory/psp/psp.go, controllers/factory/vmagent/rbac.go, controllers/vmagent_controller.go, controllers/vmalert_controller.go, controllers/vmalertmanager_controller.go, controllers/vmcluster_controller.go, controllers/vmsingle_controller.go
it must prevent bug for https://github.com/VictoriaMetrics/operator/issues/159
in case of kubernetes-controller manager removes object, it will be recreated after sync.
NOTE cluster wide objects cannot be owned by namespaced objects, in this case operator creates orphaned objects,
that cannot be deleted with garbage collection. Need to bind it to related CRD in future.
=> adds watching for owned resources

config/rbac/vmagent_editor_role.yaml, config/rbac/vmalert_editor_role.yaml, config/rbac/vmalertmanager_editor_role.yaml, config/rbac/vmnodescrape_editor_role.yaml, config/rbac/vmpodscrape_editor_role.yaml, config/rbac/vmprobe_editor_role.yaml, config/rbac/vmrule_editor_role.yaml, config/rbac/vmservicescrape_editor_role.yaml, config/rbac/vmsingle_editor_role.yaml
The current editor role manifests don't have verb `deletecollection`.
It seems there's no reason not to grant, so can I do it?
=> Add deletecollection verb to the editor roles

controllers/factory/vmcluster.go
Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>
Fix confusing logs in `createOrUpdateVMSelect` function. (possibly typo)
The logs can be found in #205
=> Fix log typo in createOrUpdateVMSelect function

controllers/factory/expansion.go
Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>
As mentioned in the #211 , the result of `Quantity.Cmp(Quantity) -> int` is not the actual diff size.
I am not sure if this modification is the most elegant way. Pls have a check.
=> Fix size diff result

config/examples/vmagent_rbac.yaml, controllers/factory/vmagent/rbac.go, hack/bundle_csv_vmagent.yaml
Failed to scrape kubelet metrics using `release/examples/vmagent_rbac.yaml`. The error logs are as follow:
> 2021-04-06T11:47:59.850Z error VictoriaMetrics/lib/promscrape/scrapework.go:255 error when scraping "https://192.168.1.1:10250/metrics" from job "kubelet" with labels {endpoint="https-metrics",instance="192.168.1.1:10250",job="kubelet",metrics_path="/metrics",namespace="kube-system",node="example.node",prometheus="default/example-vmagent",service="kubelet"}: unexpected status code returned when scraping "https://192.168.1.1:10250/metrics": 403; expecting 200; response body: "Forbidden (user=system:serviceaccount:default:vmagent-example-vmagent, verb=get, resource=nodes, subresource=metrics)"
> 2021-04-06T11:48:01.076Z error VictoriaMetrics/lib/promscrape/scrapework.go:255 error …
=> add `nodes/metrics` resource to fix scrape issue

controllers/factory/scrapes_build.go
Fixes #325. Using multiple `matchLabels` in (e.g.) a `VMPodScrape` causes infinite regenerations of the `VMAgent` configuration `Secret` due to inconsistent iteration order of the Go map holding the label key–value pairs.
Apologies for not updating `scrapes_build_test.go`; couldn’t find any existing test cases that use `matchLabels` to adapt.
=> Fix inconsistent sort order in scrape label selectors

Makefile, config/manager/manager.yaml
As stated in operator-sdk [migration.md](https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/building-operators/golang/migration.md#migrate-maingo), the environment variables `OPERATOR_NAME` and `POD_NAME` are no longer used. Let's clean them up from kustomization and makefile.
=> Remove obsolete operator-sdk environment variables

Makefile, controllers/factory/rulescm.go, controllers/factory/selectors.go, controllers/vmalertmanagerconfig_controller.go, controllers/vmnodescrape_controller.go, controllers/vmpodscrape_controller.go, controllers/vmprobe_controller.go, controllers/vmprometheusconverter_controller.go, controllers/vmrule_controller.go, controllers/vmservicescrape_controller.go, controllers/vmstaticscrape_controller.go, controllers/vmuser_controller.go, e2e/manager_test.go, e2e/suite/suite.go, e2e/watchnamespace/controllers_test.go, e2e/watchnamespace/prometheus_converter_test.go, e2e/watchnamespace/suite_test.go, e2e/watchnamespace/utils_test.go, internal/config/config.go, internal/manager/manager.go
The operator-sdk [documentation](https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/building-operators/golang/operator-scope.md#configuring-watch-namespaces-dynamically) proposes a way to restrict operator scope to a particular namespace. This feature can sometimes be very useful.
=> Add `WATCH_NAMESPACE` environment variable support

config/examples/vmalert-full.yaml
Applying the example will fail:
```
Error from server (notifier.url at idx: 1 cannot be empty): error when creating "vmalert-full.yaml": admission webhook "vmalert.victoriametrics.com" denied the request: notifier.url at idx: 1 cannot be empty
```
This probably shouldn't create two notifiers, one without an url, but
one notifier with all the attributes.
=> config/examples/vmalert-full.yaml: fix yaml

config/manifests/bases/victoriametrics-operator.clusterserviceversion.yaml
This is necessary for the operator to be displayed in the OpenShift web console OperatorHub on non-x86 architectures.
=> Add arch labels to CSV

api/v1beta1/vmalertmanager_types.go, controllers/vmalertmanager_controller.go
I'm trying to get vmagent to scrape alertmanager by default. Since I'm quite new to Golang and Kubernetes operators, please let me know if my change makes any sense :)
Fixes https://github.com/VictoriaMetrics/operator/issues/385
=> Create alertmanager service scrape by default (#385)

config/rbac/kustomization.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml
Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>
This PR intends to resolve name conflicts caused by some global resources like `clusterrole` and `clusterrolebinding`.
We are using both jaeger-operator and vm operator which shares some common names. This has incurred some permission issues in our staging cluster.
=> Add prefix to clusterrole and clusterrolebinding

api/v1beta1/vmalertmanager_types.go, api/v1beta1/vmcluster_types.go, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, config/crd/legacy/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/legacy/operator.victoriametrics.com_vmclusters.yaml, controllers/factory/alertmanager.go, controllers/factory/builders.go, controllers/factory/k8stools/annotations.go, controllers/factory/k8stools/sts.go, controllers/factory/vmcluster.go, controllers/factory/vmsingle.go, docs/api.MD
with rollingUpdateStrategy: RollingUpdate, operator doens't perform statefulset update
it delegates it to the kubernetes statefulset controller.
Default strategy is OnDelete, which controlls rolling update process by operator
RollingUpdate strategy may be useful, when user wants to perform kubectl restart command
or for some reason don't trust rolling update process for operator
Fixes annotations merge for pod templates, which make possible kubectl restart command for other services
related kubernetes issue with statefulset broken state and why manual rolling update may be needed.
https://github.com/kubernetes/kubernetes/issues/67250
https://github.com/VictoriaMetrics/operator/issues/389
=> allows to changes rolling update strategy for statefulset applications

controllers/factory/probe_build.go, controllers/factory/probe_build_test.go, controllers/factory/scrapes_build.go, controllers/factory/scrapes_build_test.go, controllers/factory/scrapes_test.go, controllers/factory/static_targets_build.go, controllers/factory/static_targets_build_test.go
Add `serviceScrape`, `podScrape`, `nodeScrape`, `staticScrape` and `probe` prefixes to `job_name` to prevent name collision. This pull request is similar to https://github.com/prometheus-operator/prometheus-operator/pull/3913 .
=> Add prefix to `job_name` to prevent name collision

controllers/factory/scrapes.go, controllers/factory/vmagent_test.go
Remote write secret is ignored when basic auth is not set. There is possibility of using other auth method without using basic auth method, e.g. bearer token.
This PR ensures that remote write secret is processed even if basic auth is not set.
=> Process remote write secret even if BasicAuth is not set

Makefile, controllers/factory/alertmanager.go, controllers/factory/builders.go, controllers/factory/finalize/common.go, controllers/factory/finalize/vmagent.go, controllers/factory/finalize/vmalert.go, controllers/factory/finalize/vmalertmanager.go, controllers/factory/finalize/vmauth.go, controllers/factory/finalize/vmcluster.go, controllers/factory/k8stools/version.go, controllers/factory/psp/psp.go, controllers/factory/vmalert.go, controllers/vmprometheusconverter_controller.go, internal/manager/manager.go
it allows to mitigate issue with deprecation policy for kubernetes and support wide range of cluster version
makes PodSecurityPolicy noop since kubernetes version 1.23
starts using PodDisruptionBudget with api v1 since kubernetes 1.22 version
https://github.com/VictoriaMetrics/operator/issues/412
=> adds kubernetes version check

controllers/factory/alertmanager/config.go, controllers/factory/alertmanager/config_test.go
Fix CRD VMAlertmanagerConfig's pagerduty_configs. The reason is similar to the issue [#339 ](https://github.com/VictoriaMetrics/operator/issues/339)，pagerduty_config wasn't rendered correctly.
Thanks.
=> fixes alertmanager pagerduty_configs generation

api/v1beta1/vmagent_types.go, api/v1beta1/vmalert_types.go, api/v1beta1/vmalertmanager_types.go, api/v1beta1/vmauth_types.go, api/v1beta1/vmcluster_types.go, api/v1beta1/vmsingle_types.go, config/crd/bases/operator.victoriametrics.com_vmagents.yaml, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/bases/operator.victoriametrics.com_vmalerts.yaml, config/crd/bases/operator.victoriametrics.com_vmauths.yaml, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, config/crd/bases/operator.victoriametrics.com_vmsingles.yaml, config/crd/legacy/operator.victoriametrics.com_vmagents.yaml, config/crd/legacy/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/legacy/operator.victoriametrics.com_vmalerts.yaml, config/crd/legacy/operator.victoriametrics.com_vmauths.yaml, config/crd/legacy/operator.victoriametrics.com_vmclusters.yaml, config/crd/legacy/operator.victoriametrics.com_vmsingles.yaml, controllers/factory/scrapes.go, controllers/factory/scrapes_test.go, controllers/factory/vmcluster.go, controllers/vmagent_controller.go, controllers/vmalert_controller.go, controllers/vmalertmanager_controller.go, controllers/vmauth_controller.go, controllers/vmsingle_controller.go, go.mod
Hi @f41gh7,
This is my 2nd pull request: kinda big and includes API changes, so I hope that it can be reviewed well before having any next actions.
This pull request solves #454 by adding `serviceScrapeSpec` on various places, so we can have more flexibility with the generated `VMServiceScrape` objects.
Thank you.
=> Allow customization of VMServiceScrape in various objects

api/v1beta1/vmagent_types.go, config/crd/bases/operator.victoriametrics.com_vmagents.yaml, config/crd/legacy/operator.victoriametrics.com_vmagents.yaml, controllers/factory/vmagent.go
In our company, we need to specify dnsConfig by our own, so I added `dnsConfig` field to vmagent spec. Please take this case into consideration and check if the way I implemented is correct. Thanks a lot. 
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/, this official doc talks about the usage of `dnsConfig`. 
Signed-off-by: Ziqi Zhao <zhaoziqi9146@gmail.com>
=> vmagent support dnsConfig

api/v1beta1/vmalertmanagerconfig_types.go, controllers/factory/alertmanager/config.go, controllers/factory/alertmanager/config_test.go
Alertmanager pagerduty_configs is missing image_config and link_config Compared with the official configuration.
=> Add image and link config into alertmanager pagerduty_configs

.github/workflows/main.yaml
This PR will update golangci-lint version to latest [v1.46.0](https://github.com/golangci/golangci-lint/tree/v1.46.0)
=> Update golangci version to latest v1.46.0

api/v1beta1/additional.go
VMStorage statefulset pvc' name should be `IntoSTSVolume` caller parameters `name`.
> This PR is to fix #482
=> Fix VMStorage statefulSet pvc create failed

api/v1beta1/additional.go, api/v1beta1/vmalertmanager_types.go
VMAlertmanager CR allows us to configure routePrefix field. If this is used, metrics is not accessible at `/metrics` (it is only accessible at `<routePrefix>/metrics`. Currently, the metrics endpoint that comes up in the generated VMServiceScrape of alertmanager is `/metrics` (even if routePrefix is configured). This PR fixes this by adding the route prefix from routePrefix field of vmalertmanager CR, so that the metrics endpoint points to the right path.
=> Fix alertmanager metrics endpoint when routePrefix is configured

api/v1beta1/vmuser_types.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/operator.victoriametrics.com_vmusers.yaml, config/crd/legacy/operator.victoriametrics.com_vmusers.yaml, controllers/factory/vmuser.go, controllers/factory/vmuser_test.go
it allows to fetch value for Bearer Token authorization at VMAuth from pre-created secret.
It works with the same rules as passwordRef
=> api/v1beta1/VMUser: adds tokenRef

api/v1beta1/vmauth_types.go, config/crd/bases/operator.victoriametrics.com_vmauths.yaml, config/crd/legacy/operator.victoriametrics.com_vmauths.yaml, controllers/factory/vmauth.go
It should allow to configure host param for non-tls ingress deployments
https://github.com/VictoriaMetrics/operator/issues/485
=> api/vmauth: adds host param for ingress

controllers/factory/alertmanager.go
See https://github.com/prometheus-operator/prometheus-operator/pull/3233
=> fix: [alertmanager] Automaticly disable high availability mode for 1 replica

controllers/factory/alertmanager.go, controllers/factory/vmagent.go, controllers/factory/vmalert.go, controllers/factory/vmauth.go, controllers/factory/vmcluster.go, controllers/factory/vmsingle.go, internal/config/config.go
This adresses #498. Tested by deploying the compiled operator with
```
env:
- name: VM_CONTAINERREGISTRY
value: harbor.local/docker.io
```
and then deploying a VMSingle instance copy&paste from https://docs.victoriametrics.com/operator/quick-start.html, resulting in
```
philipp@ ~ $ k get deployment vmsingle-example-vmsingle-persisted -o yaml | grep image:
image: harbor.local/docker.io/victoriametrics/victoria-metrics:v1.77.2
philipp@ ~ $
```
=> Add global setting to override container registry

api/v1beta1/vmalertmanager_types.go, api/victoriametrics/v1beta1/vmalertmanager_types.go, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/legacy/operator.victoriametrics.com_vmalertmanagers.yaml, controllers/factory/alertmanager.go, controllers/factory/builders.go, controllers/factory/builders_test.go, controllers/factory/vmagent.go, controllers/factory/vmalert.go, controllers/factory/vmauth.go, controllers/factory/vmcluster.go, controllers/factory/vmsingle.go
addExtraArgsOverrideDefaults: add dashes argument
Set it to `-` for all VictoriaMetrics processes, and to `--` for
alertmanager.
This fixes ExtraArgs in the VMAlertmanager resource. Previously, their
keys had to start with an extra `-`.
--
api/*/vmalertmanager_types.go: fix description for ExtraArgs, ExtraEnvs
This is not about VMAuth, but VMAlertmanager.
Fixes #502.
=> vmalertmanager: fix extraArgs, add two dashes

controllers/factory/k8stools/version.go
previosly it was incorrectly detected by operator
=> controllers: fixes policy/v1 api detection

controllers/factory/scrapes.go
Fixed scrape Authorization settings that are not propagated to VMAgent configuration
=> fixed authorization settings cache

controllers/factory/vmcluster.go
After fixing the PDB v1beta1 issue, d18954a6ccaef0659dda496c29c1efa829415e03 introduced a problem, where VMStorage does not get reconciled if it does not specify the podDisruptionBudget field.
=> Reconcile VMStorage in VMCluster even if PodDisruptionBudget does not exist

controllers/vmalertmanager_controller.go
On Kubernetes 1.25, the operator gets into a crash loop, because it tries to get policyv1beta1.PodDisruptionBudget, but it is removed in 1.25. This PR fixes that issue.
Since other resources don't have `Owns(&policyv1beta1.PodDisruptionBudget{})`, I opted to remove it. In case that is not the direction we want to go about it, feel free to change it.
=> Fix crash on Kubernetes 1.25

.github/workflows/main.yaml, .github/workflows/release.yaml
This PR will update golangci-lint version to the latest [v1.50.1](https://github.com/golangci/golangci-lint/releases/tag/v1.50.1)
=> .github/workflows: Update golangci version to latest v1.50.1

api/v1beta1/vmservicescrape_types.go, api/victoriametrics/v1beta1/vmservicescrape_types.go, controllers/factory/scrapes_build.go
Small attempt to implement VictoriaMetrics/VictoriaMetrics#3292 myself.
Gave it a shot by deploying
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
name: no-stale-marker-test
spec:
targetEndpoints:
- path: /metrics
targets:
- test.de:1234
vm_scrape_params:
no_stale_markers: false
```
and got 
```yaml
scrape_configs:
...
- job_name: staticScrape/default/no-stale-marker-test/0
metrics_path: /metrics
static_configs:
- targets:
- test.de:1234
no_stale_markers: false
```
in my VMAgent's config.
=> Expose no_stale_markers through vm_scrape_params

api/go.mod, go.mod, go.sum
Signed-off-by: yanggang <gang.yang@daocloud.io>
As [fsnotify v1.6.0](https://github.com/fsnotify/fsnotify/releases/tag/v1.6.0) released..
Follow it and improve the code .
Like 
```
if event.Op&Write == Write && !(event.Op&Remove == Remove) {
}
--->
if event.Has(Write) && !event.Has(Remove) {
}
```
=> Upgrade fsnotify to 1.6.0

controllers/factory/vmcluster.go
Prevent setting `-dedup.minScrapeInterval=1ms` if
`replicationFactor` is 1. Even 1ms has an impact on cluster's performance and behavior. 
So it is better to avoid using it at no need.
=> controllers/factory: do not set `-dedup.minScrapeInterval=1ms`

controllers/factory/k8stools/version.go
fix https://github.com/VictoriaMetrics/operator/issues/583.
autoscaling/v2beta2 is deprecated in 1.26+, use autoscaling/v2 instead.
=> [fix] Fix hpa object since v2beta deprecated in 1.26+

api/v1beta1/vmalertmanager_types.go, api/v1beta1/vmalertmanagerconfig_types.go, api/victoriametrics/v1beta1/vmalertmanager_types.go, api/victoriametrics/v1beta1/vmalertmanagerconfig_types.go, controllers/factory/alertmanager.go, controllers/factory/alertmanager/config.go, controllers/factory/alertmanager/config_test.go
fix https://github.com/VictoriaMetrics/operator/issues/615
add option `disableRouteContinueEnforce` to allow canceling the behavior for VMAlertmanagerConfig that always enforce first-level route continue to true
=> add option to disable route continue enforce

controllers/factory/vmagent.go
The operator adds single quotes to the headers inside remote write, resulting that the headers is identified as a whole string, not key:value, and when using this header to send to remote write server, the tenant that matches this header is not found.
=> Remove single quotes from remote write headers

controllers/factory/alertmanager/config.go
Although [alertmanager doc](https://prometheus.io/docs/alerting/latest/configuration/#pushover_config) don't have the sound field, but it's supported in [code](https://github.com/prometheus/alertmanager/blob/9a8d1f976e12b325ec47b84987a78b7845738be6/config/notifiers.go#L684), so does [prometheus operator](https://github.com/prometheus-operator/prometheus-operator/blob/27943fe43862d313a63b518b6ee67b59d7680c1d/pkg/apis/monitoring/v1beta1/alertmanager_config_types.go#L718).
=> vmalertmanagerconfig: support sound field in pushover config

config/webhook/manifests.yaml
This was missing in the `ValidatingWebhookConfiguration`
=> Add config for vmrule in validating webhook

api/v1beta1/additional.go, api/victoriametrics/v1beta1/additional.go, config/examples/operator_rbac_for_single_namespace.yaml, controllers/factory/finalize/common.go, controllers/factory/finalize/vmagent.go, controllers/factory/finalize/vmalertmanager.go, controllers/factory/k8stools/expansion.go, controllers/factory/psp/psp.go, controllers/factory/rulescm.go, controllers/factory/scrapes.go, controllers/factory/scrapes_build.go, controllers/factory/selectors.go, controllers/factory/vmagent.go, controllers/factory/vmagent/rbac.go, controllers/factory/vmagent/rbac_test.go, controllers/factory/vmuser.go, controllers/vmprometheusconverter_controller.go, internal/config/config.go, internal/manager/manager.go
disables cluster wide kubernetes API call with WATCH_NAMESPACE set for specific namespace. It allows to securely use operator without need to assign additional permissions for it. https://github.com/VictoriaMetrics/operator/issues/641
=> operator: allows to properly run operator with single namespace

controllers/factory/scrapes.go, controllers/factory/scrapes_test.go, controllers/factory/vmagent.go
End users may misconfigure VMPodScrape, VMServiceScrape or other object. And it breaks entire VMAgent service until admin fixes it. With those changes such objects will be skipped and VMAgent continues it's work. https://github.com/VictoriaMetrics/operator/issues/648
=> controllers/vmagent: skips misconfiguration for user defined objects

controllers/factory/alertmanager/config.go, controllers/factory/alertmanager/config_test.go
Operator will panic when vmalertmanagerconfig use WebhookConfig.URLSecret instead of WebhookConfig.URL.
So sorry for bringing it in https://github.com/VictoriaMetrics/operator/commit/89373b3ee1421fef93ec33cddea6e8a39959d02f!
=> vmalertmanagerconfig: fix panic when build webhook config

controllers/factory/vmagent.go, controllers/factory/vmauth.go, internal/config-reloader/file_watch.go, internal/config-reloader/k8s_watch.go, internal/config-reloader/main.go
implement https://github.com/VictoriaMetrics/operator/issues/619
1. add one-shot mode for config-reloader
2. use one-shot mode in initContainer if `VM_CUSTOMCONFIGRELOADERIMAGE` enabled
=> vmauth/vmagent:implement configuration initiation for custom config reloader

controllers/factory/vmauth.go, controllers/vmuser_controller.go, internal/config/config.go
If a lot of vmusers got deleted in short term, it will be rate limited now. 
So most of them will stay there until manager resync or operator restart, along with their secret.
=> vmuser: remove rate limit on delete

api/v1beta1/vmcluster_types.go, api/victoriametrics/v1beta1/vmcluster_types.go, controllers/vmcluster_controller.go
https://github.com/VictoriaMetrics/operator/issues/677
Previous check will fail when there are fields like `imagePullSecrets: []` been specified in spec, they will be omitted by json.marshall. That will cause constant status update and reconciliation for vmcluster, and possible resource update conflicts.
=> vmcluster: fix spec change check

Docker-multiarch, Makefile
Images in dockerhub now are all linux/amd64.
Looks like [release](https://github.com/VictoriaMetrics/operator/actions/runs/5070612622/jobs/9105886509) will run `make build-operator-crosscompile` && `publish-via-docker` to publish images.
=> Support publish multi-arch release

controllers/factory/alertmanager.go, controllers/factory/vmagent.go, controllers/factory/vmalert.go, controllers/factory/vmauth.go
As per the kubernetes docs (https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/), 
> If you specify a limit for a resource, but do not specify any request, and no admission-time mechanism has applied a default request for that resource, then Kubernetes copies the limit you specified and uses it as the requested value for the resource.
In the kubernetes cluster I use, there is an admission controller preventing the pods from getting created/updated if they don't have resource requests set. This change should help to fix the problem. Here is the error currently logged by victoriametrics operator that this commit should help fix:
```
cannot update deployment for app: vmagent-obs-vm, err: deployments.apps \"vmagent-obs-vm\" is forbidden: container config-reloader is …
```
=> configure resource requests for config reloader container

api/v1beta1/vmrule_types.go, api/victoriametrics/v1beta1/vmrule_types.go, config/crd/bases/operator.victoriametrics.com_vmrules.yaml, docs/CHANGELOG.MD
Add `keep_firing_for` field for vmrule, releated to https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4669
=> vmrule: support `keep_firing_for` field

controllers/factory/builders.go, controllers/factory/builders_test.go, controllers/factory/k8stools/version.go, docs/CHANGELOG.MD, internal/config/config.go
Part of https://github.com/VictoriaMetrics/operator/issues/637
1. If KubeVersion>=1.20, set `FSGroupChangePolicy: onRootMismatch`to skip the recursive permission change when the root of the volume already has the correct permissions in default PodSecurityContext.
2. SeccompProfile: Use `RuntimeDefault` seccomp profile by default, which is defined by the container runtime, instead of using the Unconfined (seccomp disabled) mode.
3. Capabilities: {Drop: []v1.Capability{"ALL"}}
=> [feature] Add more default securityContext

docs/CHANGELOG.MD
https://docs.victoriametrics.com/operator/CHANGELOG.html has some display issues.
=> fix invalid link format in changelog

api/v1beta1/vmcluster_types.go, api/victoriametrics/v1beta1/vmcluster_types.go, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, controllers/factory/scrapes.go, controllers/factory/vmcluster.go, docs/CHANGELOG.MD
After [enable strict securityContext](https://github.com/VictoriaMetrics/operator/blob/master/vars.MD#L119) in v0.36.0 by default, if `vmselect.cacheMountPath` not set, vmselect won't be start successfully cause default cache dir "/tmp" is protected. 
Fix this by using `/cache` dir and mount to emptyDir if `vmselect.cacheMountPath` not set.
Another fix is for vmselect and vmstorage, both podSecurityContext was set to non-nil, thus default podSecurityContext won't be applied to them.
=> fix vmselect cache dir mount when enableStrictSecurity

controllers/factory/vmuser.go, controllers/factory/vmuser_test.go, docs/CHANGELOG.MD
previously config was incorrectly rendered if multiple targetRef was defined
=> controllers/vmuser: fixes ip_filters indent

api/v1beta1/additional.go, api/victoriametrics/v1beta1/additional.go, controllers/factory/k8stools/sts.go, docs/CHANGELOG.MD
address https://github.com/VictoriaMetrics/operator/issues/753
remove redundant annotation `operator.victoriametrics/last-applied-spec` from created workloads like vmstorage statefulset.
=> vmcluster: remove redundant annotation from created workloads

docs/CHANGELOG.MD, internal/config/config.go, vars.MD
address https://github.com/VictoriaMetrics/operator/issues/755
upgrade default config-reloader image to [latest](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.68.0) `prometheus-config-reloader:v0.68.0`, will also introduce several good features for reloader:
1. [Set web server's ReadTimeout and ReadHeaderTimeout to 30s](https://github.com/prometheus-operator/prometheus-operator/pull/5340)
2. [add the reload-timeout argument](https://github.com/prometheus-operator/prometheus-operator/pull/5349)
3. [add SIGTERM handler](https://github.com/prometheus-operator/prometheus-operator/pull/5617)
=> upgrade default config-reloader image to latest

Makefile
| Library   | Vulnerability | Severity | Status | Installed Version | Fixed Version | Title                                                                                                      |
|-----------|---------------|----------|--------|-------------------|---------------|------------------------------------------------------------------------------------------------------------|
| libcrypto3| CVE-2023-1255 | MEDIUM   | fixed  | 3.0.8-r3          | 3.0.8-r4      | Input buffer over-read in AES-XTS implementation on 64 bit ARM [Details](https://avd.aquasec.com/nvd/cve-2023-1255)       |
|           | CVE-2023-2650 | -        | -      | -                 | 3.0.9-r0      | Possible DoS translating ASN.1 object identifiers [Details](https://avd.aquasec.com/nvd/cve-2023-2650) …
=> Bump alpine base image to latest v3.18.3

controllers/factory/k8stools/expansion.go, controllers/factory/k8stools/expansion_test.go, controllers/factory/k8stools/sts.go
follow up https://github.com/VictoriaMetrics/operator/pull/760
1. check if pvcs need to be reize as long as there is pvc since error could happen when grow pvcs and sts was updated already
2. not return error to caller if there is no point to retry when growPVC, like sc is unexpandable
If sc is unexpandable or vm opearator is under single namespace mode, pvc must be expand with user's intervention. 
Breaking reconcile and requeue under those circumstance will have no other effects except cause more pressure on cluster[list/get request and will perform sts rolling update once again].
=> controllers/k8stools: fix grow sts pvcs behavior

config/examples/operator_rbac_for_single_namespace.yaml, config/examples/vmagent_rbac.yaml, config/rbac/role.yaml, controllers/factory/vmagent/rbac.go, docs/CHANGELOG.MD, hack/bundle_csv_vmagent.yaml
Hello VictoriaMetrics team,
please correct the apiGroup for endpointsices.
tested on a local k8s cluster with single mode vm
```
cat <<EOF | k apply -f -
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
name: example-vmsingle-notpersisted
spec:
retentionPeriod: "1"
EOF
```
```
cat <<EOF | k apply -f -
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
name: example-vmagent
spec:
selectAllByDefault: true
replicaCount: 1
remoteWrite:
- url: "http://vmsingle-example-vmsingle-notpersisted.default.svc:8429/api/v1/write"
EOF
```
before the fix:
```
kubectl auth can-i get endpointslices --as=system:serviceaccount:default:vmagent-example-vmagent -n default
no
```
after the fix
```
kubectl auth can-i get endpointslices …
```
=> corrected endpointslices apigroup

controllers/factory/vmauth.go, internal/config/config.go
- Use the `--only-init-config` flag for custom configmap reloader init container in vmauth and vmagent deployments. 
- Update the default custom config reloader image to v0.38.0.
Fixes #770 .
=> Fix(vmagent, vmauth): use proper flag for custom configmap reloader init container

README.md, config/manifests/bases/victoriametrics-operator.clusterserviceversion.yaml, docs/CHANGELOG.md
Fix issue: the main issue addressed was the incorrect document links referenced throughout the project.
=> docs: fix the issue of incorrect links to referenced documents in the project

api/v1beta1/additional.go, api/v1beta1/vmagent_types.go, api/victoriametrics/v1beta1/additional.go, api/victoriametrics/v1beta1/vmagent_types.go, config/crd/bases/operator.victoriametrics.com_vmagents.yaml, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/bases/operator.victoriametrics.com_vmalerts.yaml, config/crd/bases/operator.victoriametrics.com_vmauths.yaml, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, config/crd/bases/operator.victoriametrics.com_vmsingles.yaml, docs/api.md
replace `https://victoriametrics.github.io/vmagent.html#scraping-big-number-of-targets` -> `https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets`;
refer to https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/
=> docs: fix broken links

controllers/factory/vmuser.go
When using VMUser's `vmuser.spec.targetRefs.crd` with a `VMCluster/vmselect` reference, the list of predefined path does not include `/prometheus/vmui/custom-dashboards` which causes a 400 when accessing VMUI behind VMAuth.
=> fix: add `custom-dashboards` path to VMUser's VMSelect pre-defined path

controllers/factory/vmcluster.go, docs/CHANGELOG.md
from now on operator passes `-replicationFactor` (if it set in `vmcluster`) for `vmselect` 
issue: #778
=> passing `-replicationFactor` to vmselect

controllers/factory/k8stools/expansion.go, controllers/factory/k8stools/expansion_test.go, controllers/factory/k8stools/sts.go, docs/CHANGELOG.md
1. even if statefulset needs recreate because VolumeClaimTemplates changed, sometimes pod doesn't need to be recreated. Since pod's volume only cares VolumeClaimTemplate's name, so other attributes like size or storageClassName won't effect that.
```
volumes:
- name: vmstorage-db
persistentVolumeClaim:
claimName: vmstorage-db-vmstorage-test-insight-victoria-metrics-k8s-stack-0
```
2. remove hack code from https://github.com/VictoriaMetrics/operator/issues/344, this should be resolved by https://github.com/kubernetes/kubernetes/pull/109694 and other fixes. Statefulset's currentRevision&updateRevision should be updated by statefulset controller now.
ps. also add some comments on why updating sts.Status.CurrentRevision to UpdateRevision by hand, please check if that's right @f41gh7
=> controller/factory/k8stools: optimize `HandleSTSUpdate`

docs/resources/vmrule.md
The example partially presents an alert as example instead of a recording rule. The name also contains white spaces, which is not supported.
Opening a PR here as discussed in this other PR: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5405
=> Fix wrong example in recording rules

docs/quick-start.md
`/prometheus/api/v1/status` is needed for top/active queries in vmui.
related thread https://victoriametrics.slack.com/archives/CGZF1H6L9/p1702542069333989?thread_ts=1702387812.406289&cid=CGZF1H6L9
=> add missing status route in vmauth example

Makefile
Using the [new version of alpine Linux ](https://www.alpinelinux.org/posts/Alpine-3.19.0-released.html) should fix vulnerabilities which are in previous alpine versions, see more https://artifacthub.io/packages/olm/community-operators/victoriametrics-operator/0.39.4?modal=security-report
=> Makefile: bump based alpine images to the latest v3.19.0

CONTRIBUTING.md, README.md, Release.md
1. deprecate packagemanifests;
2. some old contents are already invalid, like local test [script](https://github.com/operator-framework/community-operators/blob/master/docs/operator-test-suite.md) provided by previous repo, now we do validate when making bundle
https://github.com/VictoriaMetrics/operator/blob/2fa4c6043e52044f547c6c8f3913d41d4647977c/Makefile#L328
And there are some extra [tests](https://github.com/k8s-operatorhub/community-operators/blob/main/.github/workflows/operator_test.yaml) when creating pull requests to `https://github.com/k8s-operatorhub/community-operators` and `https://github.com/redhat-openshift-ecosystem/community-operators-prod`.
=> update operator-hub part in release doc

config/alerting/alerts-vmoperator.yaml, config/alerting/vmoperator-rules.yaml, docs/CHANGELOG.md, docs/monitoring.md
=> Add alerting rules for operator (#526)

.github/workflows/main.yaml
fix https://github.com/VictoriaMetrics/operator/actions/runs/7339857157/job/19984839742?pr=834,
`docker-operator-crosscompile` has been removed in https://github.com/VictoriaMetrics/operator/commit/c199848d02f45a0495fc031f546320b2bc471eae,
and since community job can't retrieve `secrets` for some reason, just skip the image build.
=> fix community pr workflow job

api/v1beta1/vmagent_types.go, api/v1beta1/vmalert_types.go, api/v1beta1/vmalertmanager_types.go, api/v1beta1/vmauth_types.go, api/v1beta1/vmcluster_types.go, api/v1beta1/vmsingle_types.go, api/v1beta1/zz_generated.deepcopy.go, api/victoriametrics/v1beta1/vmagent_types.go, api/victoriametrics/v1beta1/vmalert_types.go, api/victoriametrics/v1beta1/vmalertmanager_types.go, api/victoriametrics/v1beta1/vmauth_types.go, api/victoriametrics/v1beta1/vmcluster_types.go, api/victoriametrics/v1beta1/vmsingle_types.go, api/victoriametrics/v1beta1/zz_generated.deepcopy.go, config/crd/bases/operator.victoriametrics.com_vmagents.yaml, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/bases/operator.victoriametrics.com_vmalerts.yaml, config/crd/bases/operator.victoriametrics.com_vmauths.yaml, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, config/crd/bases/operator.victoriametrics.com_vmsingles.yaml, config/webhook/manifests.yaml, controllers/factory/alertmanager.go, controllers/factory/vmagent.go, controllers/factory/vmcluster.go, docs/CHANGELOG.md, docs/api.md
follow-up https://github.com/VictoriaMetrics/operator/commit/991536d212ab9dc2d81f82260d89aae877f6ba28
add `revisionHistoryLimitCount` for all the workload CRD resources, previously only for deployments.
remove dup config in validating webhook, update docs.
=> follow up https://github.com/VictoriaMetrics/operator/commit/991536d

api/client/versioned/fake/register.go, api/client/versioned/scheme/register.go, api/v1beta1/vmagent_types.go, api/v1beta1/vmalert_types.go, api/v1beta1/vmalertmanager_types.go, api/v1beta1/vmauth_types.go, api/v1beta1/vmcluster_types.go, api/victoriametrics/v1beta1/vmagent_types.go, api/victoriametrics/v1beta1/vmalert_types.go, api/victoriametrics/v1beta1/vmalertmanager_types.go, api/victoriametrics/v1beta1/vmauth_types.go, api/victoriametrics/v1beta1/vmcluster_types.go, config/crd/bases/operator.victoriametrics.com_vmagents.yaml, config/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, config/crd/bases/operator.victoriametrics.com_vmalerts.yaml, config/crd/bases/operator.victoriametrics.com_vmauths.yaml, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, controllers/factory/alertmanager.go, controllers/factory/k8stools/expansion.go, controllers/factory/k8stools/sts.go, controllers/factory/k8stools/sts_test.go, controllers/factory/vmagent.go, controllers/factory/vmagent_test.go, controllers/factory/vmalert.go, controllers/factory/vmauth.go, controllers/factory/vmcluster.go, controllers/factory/vmcluster_test.go, controllers/factory/vmsingle.go, docs/api.md, e2e/utils.go
it controls delay between pod restarts during rolling updates. It must improve rollout restart for vmstorage upgrades https://kubernetes.io/blog/2021/08/27/minreadyseconds-statefulsets/
=> api: adds MinReadySeconds param for all CRDs

docs/resources/vmalertmanager.md
The link text of AlertManager API docs was set to `VMAlert` instead of `VMAlertmanager`
=> docs/resources: fix link text for alertmanager API docs

docs/quick-start.md
Should select the demo vmuser by default.
=> fix user selector for vmauth quick-start

README.md, controllers/factory/builders.go, controllers/factory/k8stools/version.go, docs/CHANGELOG.md
address https://github.com/VictoriaMetrics/operator/issues/864,
since operator supports k8s version from 1.25 now, there is no need to have autoscaling/v2beta1.
=> remove deprecated autoscaling/v2beta1 HPA objects

controllers/converter/apis_test.go
my apologize for  vm relabeling is different from prometheus.  Due to this test case aim to probe, replace relabeling with minimal values.
cc @f41gh7
=> fix(apis_test.go): fix relabeling config

config/examples/vmcluster_storage_class_unexpandable.yaml, controllers/factory/k8stools/expansion.go
previously each pvc created by sts must be annotated with operator.victoriametrics.com/pvc-allow-volume-expansion now, it's no longer needed, operator performs a check on sts claim definition itself it allows to use it for PVC autoscaler or simmilar tool https://github.com/VictoriaMetrics/operator/issues/867
=> controllers: properly check annotations at sts claim template

controllers/factory/vmalert.go, docs/CHANGELOG.md
Previously, setting "notifier.blackhole" and not using any notifiers would lead to CrashLoopBackoff because vmalert would receive an empty "notifier.url" value.
Updates:
- https://github.com/VictoriaMetrics/operator/issues/894
- https://github.com/VictoriaMetrics/operator/pull/813
=> controllers/factory/vmalert: do not add `notifier.*` flags if `notifier.blackhole` is set by user

controllers/factory/builders.go, controllers/factory/builders_test.go
Fixes #896
Don't use hardcoded `HTTP` for liveness probe.
=> Fix livenessProbe scheme

api/v1beta1/vmalertmanagerconfig_types.go, api/v1beta1/vmcluster_types.go, api/victoriametrics/v1beta1/vmalertmanagerconfig_types.go, config/crd/bases/operator.victoriametrics.com_vmclusters.yaml, config/crd/bases/operator.victoriametrics.com_vmsingles.yaml, config/examples/operator_rbac_for_single_namespace.yaml, config/manifests/bases/victoriametrics-operator.clusterserviceversion.yaml, config/rbac/role.yaml, docs/CHANGELOG.md
1. follow up https://github.com/VictoriaMetrics/operator/commit/a54efbc647b0e099a583885afa263aa9fc2f9853, fix type struct field tags
2. remove unnecessary pod permission for operator, see https://github.com/VictoriaMetrics/operator/issues/902
3. remove fields `VMClusterSpec.VMInsert.Name`, `VMClusterSpec.VMStorage.Name`, `VMClusterSpec.VMSelect.Name`, they're marked as deprecated since v0.21.0 in https://github.com/VictoriaMetrics/operator/commit/141c82370da6f27fd32502dc14709e844978778a.
=> chore: minor fixes

config/rbac/kustomization.yaml
https://github.com/VictoriaMetrics/operator/commit/aec40dba892f2d0a23537ab5cf80d732e6c4b31d removed the kustomize files related to the psp, but the patch remained. Remove this.
=> config: removes unused patch

controllers/factory/alertmanager/alertmanager_test.go, controllers/factory/reconcile/deploy.go, controllers/factory/reconcile/statefulset.go, controllers/factory/reconcile/statefulset_pvc_expand.go, controllers/factory/reconcile/statefulset_test.go, controllers/factory/vmagent/rbac.go, controllers/factory/vmagent/vmagent.go, controllers/factory/vmalert/vmalert.go, controllers/factory/vmauth/vmauth.go, controllers/factory/vmcluster/vmcluster.go, controllers/factory/vmcluster/vmcluster_test.go, controllers/factory/vmsingle/vmsingle.go, docs/CHANGELOG.md, e2e/utils.go
it ensures, that all pods for statefulset is ready to serve requests. It must fix an issue when newly created cluster has operational status, when in fact pod is still not at ready state.
Adds more context to the wait timeout error. Reason of pod not to be ready. It must help to debug possible issues with pod configuration.
Deletes few typos.
=> controllers/reconcile: adds waitReady function for statefulset

controllers/factory/finalize/common.go, docs/CHANGELOG.md
It must possible issues with JSON marshalling mutations and remove default values setting for CRD object.
Previously, it was possible, that object was modified during unmarshalling, it causes object mutation after client.Update call. Since object state wasn't restored to the original version after marshalling.
https://github.com/VictoriaMetrics/operator/issues/946
=> controllers: use client.Patch for finalizers mutations instead of Update

controllers/converter/apis.go, controllers/converter/apis_test.go, docs/CHANGELOG.md
This patches fixes the owner reference type for VMScrapeConfig objects. Without this patch, on many clusters, newly-created VMScrapeConfig objects would immediately be deleted because the owner reference would not resolve.
=> controllers/prometheus-converter: fix owner reference type for VMScrapeConfig

api/victoriametrics/v1beta1/vmalertmanager_webhook.go, controllers/factory/alertmanager/config_test.go, controllers/factory/alertmanager/statefulset.go, docs/CHANGELOG.md
Ignores any content from secret define at cr.spec.configSecret, if it name clashes with name of the secret created by operator.
https://github.com/VictoriaMetrics/operator/issues/954
=> vmalertmanager: ignore content of configSecret if name clashes with default

controllers/factory/alertmanager/statefulset.go, controllers/factory/finalize/common.go, controllers/factory/reconcile/deploy.go, controllers/factory/reconcile/hpa.go, controllers/factory/reconcile/pdb.go, controllers/factory/reconcile/service.go, controllers/factory/reconcile/service_account.go, controllers/factory/reconcile/statefulset.go, controllers/factory/reconcile/vmservicescrape.go, controllers/factory/vmagent/rbac.go, controllers/factory/vmagent/vmagent.go, controllers/factory/vmagent/vmagent_scrapeconfig.go, controllers/factory/vmalert/rules.go, controllers/factory/vmalert/vmalert.go, controllers/factory/vmauth/rbac.go, controllers/factory/vmauth/vmauth.go, controllers/factory/vmsingle/vmsingle.go, docs/CHANGELOG.md
Kubernetes performs soft delete and waits for object hard delete until finalizers == 0. During that period any actions for soft deleted objects aren't performend. It caues weird behavior for service accounts, deployments and etc. When kubernetes-controller manager ignores actions that must be performend with it. For instance, pod creation for soft deleted deployment.
Operator now detects soft delete and free objects. An object ll be recreate at the next reconcile loop and error message ll be logged.
https://github.com/VictoriaMetrics/operator/issues/953
=> controllers/finalize: Remove finalizer for child objects for non zero DeletionTimestamp

Docker-multiarch, Makefile
Added scratch images for operator
=> added scratch images

controllers/vmalertmanagerconfig_controller.go, docs/CHANGELOG.md
Fixes missing err handkle func after bc09a9b
=> controllers/vmalertmanagerconfig: adds missing err handle callback

.github/workflows/operatorhub.yaml, Makefile, config/manifests/bases/victoriametrics-operator.clusterserviceversion.yaml, config/manifests/kustomization.yaml, config/manifests/scorecard.yaml, internal/manager/manager.go
- set maxdepth in find to 0 to exclude child dirs
- fixed openshift version boundaries
- exclude docs and config folders from image tag hash calculation
- properly override makefile dependency targets variables
- fixed typo in operator logging
- added scorecards for olm bundle
=> fixed replaced version extraction

docs/resources/vmalertmanager.md
Fixing typo in what would be honored for configuration if secret and raw values, both are provided.
=> Update vmalertmanager.md to fix typo in doc

docs/CHANGELOG.md, internal/controller/operator/factory/finalize/common.go
Previously name and namespace args were misplaced at removeFinalize function call. It prevented from proper object deletion. And caused various errors during objects deletion.
https://github.com/VictoriaMetrics/operator/issues/1036
=> internal/finalize: fixes typo at PDB delete function

api/operator/v1beta1/vmscrapeconfig_types.go, config/crd/overlay/crd.yaml, docs/CHANGELOG.md, internal/controller/operator/factory/vmagent/scrapeconfig.go, internal/controller/operator/factory/vmagent/scrapeconfig_test.go
Related to https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6434
=> vmscrapeconfig: support max_scrape_size option

api/operator/v1beta1/vmuser_types.go, api/operator/v1beta1/vmuser_webhook.go, config/crd/overlay/crd.yaml, docs/CHANGELOG.md, docs/api.md, internal/controller/operator/factory/k8stools/test_helpers.go, internal/controller/operator/factory/vmauth/vmusers_config.go, internal/controller/operator/factory/vmauth/vmusers_config_test.go
Changes behaviour of VMAuth config generation:
* now it skips misconfigured VMUser objects and continues config generation without it
* misconfigured VMUsers marked with error at lastSyncError field
* configuration checks better for misconfiguration (properly deduplicate user tokens, checks static url links and result url_map)
Performs refactoring for CRDRef fetching. Use generic interface and reduce copy-paste.
Introduce new status field for VMUser - `lastSyncError`. Adds column print for it.
https://github.com/VictoriaMetrics/operator/issues/1047
=> api/vmuser: adds status.lastSyncError

docs/CHANGELOG.md, docs/setup.md, internal/controller/operator/converter/v1alpha1/apis.go, internal/controller/operator/converter/v1alpha1/apis_test.go
related https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6790
also fixes #1073
=> fixed kustomize docs

api/operator/v1beta1/vmagent_types.go, api/operator/v1beta1/vmalertmanager_types.go, api/operator/v1beta1/vmcluster_types.go, docs/CHANGELOG.md, internal/controller/operator/factory/alertmanager/alertmanager.go, internal/controller/operator/factory/alertmanager/alertmanager_test.go, internal/controller/operator/factory/alertmanager/statefulset.go, internal/controller/operator/factory/build/statefulset.go, internal/controller/operator/factory/reconcile/statefulset.go, internal/controller/operator/factory/reconcile/statefulset_pvc_expand.go, internal/controller/operator/factory/vmagent/vmagent.go, internal/controller/operator/factory/vmcluster/vmcluster.go, internal/controller/operator/factory/vmcluster/vmcluster_test.go
* Previous commit made incorrect equal check to revisionHistoryLimit, since kubernetes automatically sets default value for revisionHistory and some other fields. It fails operator check and re-creates statefulset on each reconcile loop.
* with this change operator will set default values to generated statefulset. It must fix this issue and prevent possible future misconfiguration.
related issues
https://github.com/VictoriaMetrics/helm-charts/issues/1319 https://github.com/VictoriaMetrics/operator/issues/1070
=> reconcile: fixes statefulset endless reconcile loop

docs/CHANGELOG.md, internal/config/config.go
Following https://docs.victoriametrics.com/release-guide/#bump-the-version-of-images
=> internal/config: bump vm version to 1.103.0

internal/controller/operator/factory/finalize/vmagent.go, internal/controller/operator/factory/finalize/vmalert.go, internal/controller/operator/factory/finalize/vmalertmanager.go, internal/controller/operator/factory/finalize/vmauth.go, internal/controller/operator/factory/finalize/vmcluster.go
Fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6994
This PR adds a missing check to PDB during `finalize()` phase, and skips if its not enabled. (Tested on our clusters and can confirm it works!)
=> controllers/finalizers: respect the enabled status of PDB

internal/config/config.go
Please note, I followed https://docs.victoriametrics.com/release-guide/#operator and it seems incorrect starting on step 2. Please, update the release guide according to the expected procedures for VM version update.
=> internal/config: bump vm version to 1.104.0

docs/CHANGELOG.md, internal/controller/operator/factory/reconcile/statefulset.go
Previously, during Deployment -> StatefulSet transition, it was possible to be in state, where deployment was not scheduled successfully. If `VMAgent` spec changed into `statefulMode`, operator incorrectly lists pods that belong to `Deployment` for sts rolling update.
It produces error and could only be fixed by manual `Deployment` deletion.
This commit filters all pods, that don't have `StatefulSet` in `OwnerReferences`. It fixes incorrect behavior of this kind of transition.
Related issue: https://github.com/VictoriaMetrics/operator/issues/1127
=> reconcile/statefulset: fixes vmagent statefulmode transition

docs/CHANGELOG.md, internal/controller/operator/factory/build/security.go, test/e2e/vmauth_test.go, test/e2e/vmsingle_test.go
It allow to use strictSecurity with hosts without AppArmor and Seccomp (windows nodes for instance). This change doesn't affect security, neither adds breaking changes, since AppArmor and Seccomp are rarely used. And set by default to the same values, as operator added.
Related issue https://github.com/VictoriaMetrics/operator/issues/1120
=> build/security: removes AppArmorProfile and SeccompProfile from defaults

api/operator/v1beta1/vmalertmanager_types.go, docs/CHANGELOG.md, internal/controller/operator/factory/alertmanager/statefulset.go, internal/controller/operator/factory/vmagent/vmagent.go, internal/controller/operator/factory/vmauth/vmauth.go, internal/controller/operator/factory/vmcluster/vmcluster.go, internal/controller/operator/factory/vmsingle/vmsingle.go, test/e2e/vmagent_test.go, test/e2e/vmalertmanager_test.go, test/e2e/vmauth_test.go
Previously strictSecurity was added to the operator defined initContainer only if there is user-defined initContainers. This logic is incorrect.
Operator must apply strict security configuration only to the containers created on its own.
All security related settings for side-car and initContainers must be managed by operator's users.
This commit fixes incorrect logic and properly apply strict security params to the init containers.
Affected CRDs - VMAgent, VMAuth and VMAlertmanager.
Added tests to verify this logic.
Related issue:
https://github.com/VictoriaMetrics/operator/issues/1134
=> controller/security: properly add strictSecurity to initContainers

docs/CHANGELOG.md, internal/controller/operator/factory/alertmanager/statefulset.go
Properly include ConfigMaps provided via `.spec.configMaps` into a list of watched directories in order to trigger the reload.
Previously, a user-defined `ConfigMap` change would require a manual reload trigger or an additional sidecar.
=> controller/operator/factory/alertmanager: include `.spec.configMaps` to config-reloader

internal/controller/operator/factory/reconcile/statefulset.go
Relates to https://github.com/VictoriaMetrics/operator/issues/744
Currently with larger vmclusters that may need more time to handle vmstorage rollouts, there's a `storage.vminsertConnsShutdownDuration` flag we can use to handle gracefully closing connections to vminsert while it rolls out. However the issue we're running into is that the operator uses a hard-coded value of 30s to set the grace period for delete, so we increasing the value used for the `storage.vminsertConnsShutdownDuration` flag doesn't help since vmstorage pods will always be killed after 30 seconds.
=> feat: allow dynamic config of terminationGracePeriodSeconds to work with storage.vminsertConnsShutdownDuration flag

docs/CHANGELOG.md, internal/controller/operator/factory/k8stools/test_helpers.go, internal/controller/operator/factory/reconcile/deploy.go, internal/controller/operator/factory/reconcile/deploy_test.go
The algorithm is taken from the `kubectl rollout status` command.
Currently (before this update), the operator sets status operational ahead of time - when vmsingle pods are still restarting.
=> Fixed deployment readiness (operational status) detection after resource update

api/operator/v1beta1/vmextra_types.go, config/crd/overlay/crd.yaml, docs/api.md
relates to https://github.com/VictoriaMetrics/helm-charts/pull/1902
=> Fix "minim number os seconds" typo 

api/operator/v1beta1/vmauth_types.go
Due to a logic bug in `VMAuth.IsUnmanaged()`, the VMUser reconiliation does not update the corresponding VMAuth resources' configuration:
https://github.com/VictoriaMetrics/operator/blob/master/internal/controller/operator/vmuser_controller.go#L99
This bug is hidden/mitigated currently because the VMAuth reconciliation by default is requeued every 60 seconds:
https://github.com/VictoriaMetrics/operator/blob/master/internal/controller/operator/vmauth_controller.go#L101
=> vmuser: fix reconciling the vmauth config

internal/controller/operator/factory/vmagent/vmagent.go
This arg is currently set twice for vmagent. Once [here](https://github.com/solidDoWant/operator/blob/b26dcb35ccf227079a5bf0506d722c24d7dc6b41/internal/controller/operator/factory/vmagent/vmagent.go#L610-L611), and once on the on (the now deleted) line 448. This results in it being passed twice in the pod spec.
=> Fix vmagent instances setting license args twice

.github/workflows/docs.yaml
changed working-directory, property, which is not supported for 3rd-party actions to proper go.mod path
=> replaced not-supported working-directory with proper go.mod path

docs/resources/vmauth.md
Hello,
I think the example should use replicaCount instead of replicas (https://docs.victoriametrics.com/operator/api/#vmauthspec-replicacount).
Thank you :)
=> Fix doc VMAuth HA example

docs/resources/vmpodscrape.md, docs/resources/vmservicescrape.md
Some info about namespaceSelector being empty was a bit misleading :)
=> fix and unify namespaceSelector description in VMPodScrape and VMServiceScrape

api/operator/v1beta1/vmcluster_types.go, docs/CHANGELOG.md, internal/controller/operator/factory/vmcluster/vmcluster.go
The VMCluster request load balancer resource currently completely ignores the pod metadata field. This PR sets the load balancer labels and annotations in the same way that other they're set for other components.
=> Fix request load balancer ignoring pod metadata

internal/config/config.go
[This commit](https://github.com/VictoriaMetrics/operator/commit/f0aa09cd76ed3a2918085b14cf3f5e4037d98a92) removed the `s` from the default `VLog` container image tag. [As shown here](https://hub.docker.com/layers/victoriametrics/victoria-logs/v1.17.0-victorialogs/images/sha256-cc9bee8039d8e03eaf62a3ecb77ed6b389509f9ed1cb10a3626d137d7580bb2c), the tag should end in `victorialogs` not `victorialog`.
=> Fix VLogs resource using invalid image tag by default

internal/controller/operator/factory/alertmanager/config.go
When using rocketchat in alertmanager for alert, it appears same secret value gets inserted both into _token_id_ and _token_, although a different secret key is referenced in VmAlertManagerConfig.
```yaml
...
rocketchat_configs:
- api_url: <url>
channel: <channel>
token:
name: alertmanager
key: rocketchat_token
token_id:
name: alertmanager
key: rocketchat_token_id
....
```
I think I located the issue in _config.go_, where the wrong variable is used to retrieve the secret value.
=> fix: use correct TokenId value when building rocketchat config

docs/CHANGELOG.md, internal/controller/operator/factory/vmagent/vmagent.go
This flag has a typo, which causes vmagent to crash when the VMAgent custom resource's `spec.remoteWrite[x].streamAggrConfig.enableWindows` flag is set to true.
=> Fix typo in streamAggr vmagent flag

Makefile, docs/Makefile
Locally I was getting the error because of undefined UID var. I've fixed it alinging the solution with how docs organized in VictoriaMetrics repo.
```
...
3.531 OK: 33 MiB in 44 packages
5.535 adduser: uid '0' in use
------
Dockerfile:14
--------------------
13 |
14 | >>> RUN \
15 | >>>   apk add \
16 | >>>     curl \
17 | >>>     jq \
18 | >>>     libstdc++ \
19 | >>>     libwebp-tools \
20 | >>>     gcompat && \
21 | >>>   apk add
--repository=http://dl-cdn.alpinelinux.org/alpine/edge/main/ \
22 | >>>     icu-libs && \
23 | >>>   apk add
--repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
24 | >>>     dart-sass && \
25 | >>>   curl \
26 | >>>     -fsSL ${HUGO_URL} \
27 | >>>     --output hugo.tar.gz && \
28 | >>>   tar -xzf hugo.tar.gz && \
29 | >>>   mv hugo /usr/bin/ && …
```
=> docs: Fix docker build uid issue. Move docs related make commands into docs dir. Move docs tasks into docs/Makefile.

docs/quick-start.md
Previous related PRs:
- https://github.com/VictoriaMetrics/operator/pull/1328
- https://github.com/VictoriaMetrics/operator/pull/1331
STR: https://github.com/VictoriaMetrics/debug-notes/pull/3
=> docs: quick start alerting section

docs/resources/vlogs.md
The apiVersion was missing in the example CRD for VLogs in the documentation. In this merge request, I’ve added it.
=> docs: add apiVersion to example VLogs CRD

Makefile, config/default/metrics_service.yaml, config/manager/manager.yaml, config/webhook/service.yaml, docs/quick-start.md, docs/release-guide.md
The goal of this update is to ensure that the examples in the Operator quick start guide are also applicable when the Operator is installed via Helm charts.
Fixes https://github.com/VictoriaMetrics/operator/issues/1337
Tested in Kind with https://github.com/VictoriaMetrics/debug-notes/tree/main/operator/quick-start,
installed v0.58.0, than this version, than again v0.58.0. worked
=> config: sync installer operator labels with Helm-installed version

README.md, docs/CHANGELOG.md, docs/FAQ.md, docs/configuration.md, docs/env.md, docs/quick-start.md, docs/vars.md, internal/config/print.go
PR Enhance the operator configuration via env variables. 
Example:
Scripts https://github.com/VictoriaMetrics/debug-notes/pull/7
=> docs/configuration: Enchance env variables related stuff

docs/CHANGELOG.md, internal/controller/operator/converter/apis.go, internal/controller/operator/converter/apis_test.go
In case when filtering prefixes more than one per label or annotation filtering doesn't work.
```
VM_FILTERPROMETHEUSCONVERTERLABELPREFIXES=filter-1,filter-2
VM_FILTERPROMETHEUSCONVERTERANNOTATIONPREFIXES=filter-1,filter-2
```
This PR fixes an issue.
=> Fix for filtering Prometheus Operator's object labels/annotations

internal/controller/operator/factory/vmagent/nodescrape.go, internal/controller/operator/factory/vmagent/nodescrape_test.go, internal/controller/operator/factory/vmagent/vmagent_scrapeconfig.go, internal/controller/operator/factory/vmagent/vmagent_scrapeconfig_test.go
job name for scrapes has a following convention `<scrape-type>/<scrape-name>/<idx>` when multiple targets are available in scrape configuration and `<scrape-type>/<scrape-name>`, when a single target can be configured. nodescrape has a single target configurable but for some reason its job name uses`nodescrape/<scrape-name>/<idx>` naming. this PR removes confusing index from nodescrape job name
=> removed unneeded id from nodescrape target name

.github/workflows/close-pr.yaml, .github/workflows/crds.yaml, .github/workflows/docs.yaml, .github/workflows/main.yaml, .github/workflows/operatorhub.yaml, .github/workflows/sandbox.yaml, .gitignore, Makefile, test/e2e/childobjects/vmalertmanagerconfig_test.go, test/e2e/childobjects/vmrule_test.go, test/e2e/childobjects/vmuser_test.go, test/e2e/suite/suite.go, test/e2e/vlcluster_test.go, test/e2e/vlsingle_test.go, test/e2e/vmagent_test.go, test/e2e/vmalert_test.go, test/e2e/vmalertmanager_test.go, test/e2e/vmanomaly_test.go, test/e2e/vmauth_test.go, test/e2e/vmcluster_test.go, test/e2e/vmsingle_test.go
- run e2e tests in paralllel
- removed operator images build and publishing for non-release builds, since it takes lots of CI time
- added permissions to all CI jobs, which are suggested by github
- CI time reduced from about 40 mins to up to 15 mins
- added JUnit test report
=> run e2e in parallel

api/operator/v1beta1/common_scrapeparams.go, api/operator/v1beta1/vmagent_types.go, api/operator/v1beta1/vmalert_types.go, api/operator/v1beta1/vmauth_types.go, api/operator/v1beta1/vmcluster_types.go, api/operator/v1beta1/vmextra_types.go, api/operator/v1beta1/vmrule_types.go, api/operator/v1beta1/vmscrapeconfig_types.go, api/operator/v1beta1/vmsingle_types.go, api/operator/v1beta1/vmuser_types.go, config/crd/overlay/crd.yaml, docs/api.md
added trailing slash to path and /victoriametrics prefix to all docs references where it's needed
=> docs: fixed links in CRDs and API docs

config/examples/kustomization.yaml
=> olm: added absent examples for VLCluster and VLSingle

docs/CHANGELOG.md, internal/controller/operator/factory/vmagent/servicescrape_test.go, internal/controller/operator/factory/vmagent/vmagent_scrapeconfig.go
A config marshalling will not add `tls_config` to store the config for scrape configurations at vmagent since 8df334cc.
=> internal/controller/operator/factory/vmagent: fix tls config marshalling

docs/CHANGELOG.md, internal/controller/operator/factory/reconcile/daemonset.go, internal/controller/operator/factory/reconcile/deploy.go, internal/controller/operator/factory/reconcile/deploy_test.go, internal/controller/operator/factory/reconcile/statefulset.go, internal/controller/operator/factory/reconcile/statefulset_pvc_expand.go, internal/controller/operator/factory/reconcile/statefulset_test.go, internal/controller/operator/factory/vlagent/vlagent_test.go, internal/controller/operator/factory/vmagent/vmagent_test.go
When `immediate` flag is unset, this function waits for `interval` first and only afterward runs the function the first time. This commit changes all function calls to use `immediate` true to make it run sooner.
With [tracing](https://github.com/vrutkovs/operator/tree/tracing) the effects of these flags is most obvious.
Before:
`reconcile.waitDeploymentReady` doesn't do anything for a second and then runs `client.Get`
After:
Now `reconcile.waitDeploymentReady` takes 25 nanoseconds and runs `client.Get` immediately
Unfortunately I didn't get a chance to test this PR properly, as it affects a lot of areas in operators, but I can't think of a reason why would it cause regressions.
=> controller/operator/factory: run PollUntilContextTimeout with immediate flag

docs/CHANGELOG.md, internal/controller/operator/factory/reconcile/service.go, internal/controller/operator/factory/reconcile/service_test.go
Previously, operator produced runtime error:
```
cannot reconcile additional service for CRD: Service "CRD-NAME" is invalid: spec.loadBalancerClass: Invalid value: "null": may not change once set
```
This commit adds `Service` re-creation on field change. It's expected
that `Service` `IP` will be changed. And it may interrupt communication with application.
=> reconcile/service: properly handle loadbalancerClass field change

docs/setup.md
VM and operator are supported on a set of architectures, not just ARM. Let's mention those explicitly
=> fix: update setup docs to mention other architectures

api/operator/v1/vmanomaly_types.go, config/crd/overlay/crd.yaml, docs/CHANGELOG.md, internal/controller/operator/factory/build/defaults.go, internal/controller/operator/factory/vmanomaly/config/config.go, internal/controller/operator/factory/vmanomaly/config/monitoring.go, internal/controller/operator/factory/vmanomaly/config/readers.go, internal/controller/operator/factory/vmanomaly/config/schedulers.go, internal/controller/operator/factory/vmanomaly/config/writers.go, internal/controller/operator/factory/vmanomaly/pod.go
fixes https://github.com/VictoriaMetrics/operator/issues/1538
allow providing empty reader, writer, models and schedulers sections, when spec.configRawYaml.preset is equal to ui
=> vmanomaly: support ui preset mode

internal/controller/operator/factory/reconcile/service.go, internal/controller/operator/factory/reconcile/service_test.go, internal/controller/operator/factory/vmcluster/vmcluster.go
When reconciling k8s services managed by the operator, custom labels, such as those added by mutating webhooks, the user, or third-party controllers are clobbered. Resolves #1533.
=> Fix: conserve custom labels on services
